package com.dandelion.memberapp.model.po;

import java.util.Date;

public class Emailbean {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_emailbean.ID
	 * @mbggenerated  Thu Jan 16 19:58:43 CST 2014
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_emailbean.token
	 * @mbggenerated  Thu Jan 16 19:58:43 CST 2014
	 */
	private String token;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_emailbean.expire
	 * @mbggenerated  Thu Jan 16 19:58:43 CST 2014
	 */
	private Date expire;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_emailbean.ID
	 * @return  the value of tb_emailbean.ID
	 * @mbggenerated  Thu Jan 16 19:58:43 CST 2014
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_emailbean.ID
	 * @param id  the value for tb_emailbean.ID
	 * @mbggenerated  Thu Jan 16 19:58:43 CST 2014
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_emailbean.token
	 * @return  the value of tb_emailbean.token
	 * @mbggenerated  Thu Jan 16 19:58:43 CST 2014
	 */
	public String getToken() {
		return token;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_emailbean.token
	 * @param token  the value for tb_emailbean.token
	 * @mbggenerated  Thu Jan 16 19:58:43 CST 2014
	 */
	public void setToken(String token) {
		this.token = token;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_emailbean.expire
	 * @return  the value of tb_emailbean.expire
	 * @mbggenerated  Thu Jan 16 19:58:43 CST 2014
	 */
	public Date getExpire() {
		return expire;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_emailbean.expire
	 * @param expire  the value for tb_emailbean.expire
	 * @mbggenerated  Thu Jan 16 19:58:43 CST 2014
	 */
	public void setExpire(Date expire) {
		this.expire = expire;
	}
}