package com.dandelion.memberapp.model.po;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class FeedExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table tb_feed
	 * @mbggenerated  Tue Dec 31 16:48:21 CST 2013
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table tb_feed
	 * @mbggenerated  Tue Dec 31 16:48:21 CST 2013
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table tb_feed
	 * @mbggenerated  Tue Dec 31 16:48:21 CST 2013
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_feed
	 * @mbggenerated  Tue Dec 31 16:48:21 CST 2013
	 */
	public FeedExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_feed
	 * @mbggenerated  Tue Dec 31 16:48:21 CST 2013
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_feed
	 * @mbggenerated  Tue Dec 31 16:48:21 CST 2013
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_feed
	 * @mbggenerated  Tue Dec 31 16:48:21 CST 2013
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_feed
	 * @mbggenerated  Tue Dec 31 16:48:21 CST 2013
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_feed
	 * @mbggenerated  Tue Dec 31 16:48:21 CST 2013
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_feed
	 * @mbggenerated  Tue Dec 31 16:48:21 CST 2013
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_feed
	 * @mbggenerated  Tue Dec 31 16:48:21 CST 2013
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_feed
	 * @mbggenerated  Tue Dec 31 16:48:21 CST 2013
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_feed
	 * @mbggenerated  Tue Dec 31 16:48:21 CST 2013
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_feed
	 * @mbggenerated  Tue Dec 31 16:48:21 CST 2013
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table tb_feed
	 * @mbggenerated  Tue Dec 31 16:48:21 CST 2013
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("ID is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("ID is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Long value) {
			addCriterion("ID =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Long value) {
			addCriterion("ID <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Long value) {
			addCriterion("ID >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Long value) {
			addCriterion("ID >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Long value) {
			addCriterion("ID <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Long value) {
			addCriterion("ID <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Long> values) {
			addCriterion("ID in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Long> values) {
			addCriterion("ID not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Long value1, Long value2) {
			addCriterion("ID between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Long value1, Long value2) {
			addCriterion("ID not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andUseridfkIsNull() {
			addCriterion("UserIDFK is null");
			return (Criteria) this;
		}

		public Criteria andUseridfkIsNotNull() {
			addCriterion("UserIDFK is not null");
			return (Criteria) this;
		}

		public Criteria andUseridfkEqualTo(Long value) {
			addCriterion("UserIDFK =", value, "useridfk");
			return (Criteria) this;
		}

		public Criteria andUseridfkNotEqualTo(Long value) {
			addCriterion("UserIDFK <>", value, "useridfk");
			return (Criteria) this;
		}

		public Criteria andUseridfkGreaterThan(Long value) {
			addCriterion("UserIDFK >", value, "useridfk");
			return (Criteria) this;
		}

		public Criteria andUseridfkGreaterThanOrEqualTo(Long value) {
			addCriterion("UserIDFK >=", value, "useridfk");
			return (Criteria) this;
		}

		public Criteria andUseridfkLessThan(Long value) {
			addCriterion("UserIDFK <", value, "useridfk");
			return (Criteria) this;
		}

		public Criteria andUseridfkLessThanOrEqualTo(Long value) {
			addCriterion("UserIDFK <=", value, "useridfk");
			return (Criteria) this;
		}

		public Criteria andUseridfkIn(List<Long> values) {
			addCriterion("UserIDFK in", values, "useridfk");
			return (Criteria) this;
		}

		public Criteria andUseridfkNotIn(List<Long> values) {
			addCriterion("UserIDFK not in", values, "useridfk");
			return (Criteria) this;
		}

		public Criteria andUseridfkBetween(Long value1, Long value2) {
			addCriterion("UserIDFK between", value1, value2, "useridfk");
			return (Criteria) this;
		}

		public Criteria andUseridfkNotBetween(Long value1, Long value2) {
			addCriterion("UserIDFK not between", value1, value2, "useridfk");
			return (Criteria) this;
		}

		public Criteria andContentIsNull() {
			addCriterion("Content is null");
			return (Criteria) this;
		}

		public Criteria andContentIsNotNull() {
			addCriterion("Content is not null");
			return (Criteria) this;
		}

		public Criteria andContentEqualTo(String value) {
			addCriterion("Content =", value, "content");
			return (Criteria) this;
		}

		public Criteria andContentNotEqualTo(String value) {
			addCriterion("Content <>", value, "content");
			return (Criteria) this;
		}

		public Criteria andContentGreaterThan(String value) {
			addCriterion("Content >", value, "content");
			return (Criteria) this;
		}

		public Criteria andContentGreaterThanOrEqualTo(String value) {
			addCriterion("Content >=", value, "content");
			return (Criteria) this;
		}

		public Criteria andContentLessThan(String value) {
			addCriterion("Content <", value, "content");
			return (Criteria) this;
		}

		public Criteria andContentLessThanOrEqualTo(String value) {
			addCriterion("Content <=", value, "content");
			return (Criteria) this;
		}

		public Criteria andContentLike(String value) {
			addCriterion("Content like", value, "content");
			return (Criteria) this;
		}

		public Criteria andContentNotLike(String value) {
			addCriterion("Content not like", value, "content");
			return (Criteria) this;
		}

		public Criteria andContentIn(List<String> values) {
			addCriterion("Content in", values, "content");
			return (Criteria) this;
		}

		public Criteria andContentNotIn(List<String> values) {
			addCriterion("Content not in", values, "content");
			return (Criteria) this;
		}

		public Criteria andContentBetween(String value1, String value2) {
			addCriterion("Content between", value1, value2, "content");
			return (Criteria) this;
		}

		public Criteria andContentNotBetween(String value1, String value2) {
			addCriterion("Content not between", value1, value2, "content");
			return (Criteria) this;
		}

		public Criteria andUrlIsNull() {
			addCriterion("URL is null");
			return (Criteria) this;
		}

		public Criteria andUrlIsNotNull() {
			addCriterion("URL is not null");
			return (Criteria) this;
		}

		public Criteria andUrlEqualTo(String value) {
			addCriterion("URL =", value, "url");
			return (Criteria) this;
		}

		public Criteria andUrlNotEqualTo(String value) {
			addCriterion("URL <>", value, "url");
			return (Criteria) this;
		}

		public Criteria andUrlGreaterThan(String value) {
			addCriterion("URL >", value, "url");
			return (Criteria) this;
		}

		public Criteria andUrlGreaterThanOrEqualTo(String value) {
			addCriterion("URL >=", value, "url");
			return (Criteria) this;
		}

		public Criteria andUrlLessThan(String value) {
			addCriterion("URL <", value, "url");
			return (Criteria) this;
		}

		public Criteria andUrlLessThanOrEqualTo(String value) {
			addCriterion("URL <=", value, "url");
			return (Criteria) this;
		}

		public Criteria andUrlLike(String value) {
			addCriterion("URL like", value, "url");
			return (Criteria) this;
		}

		public Criteria andUrlNotLike(String value) {
			addCriterion("URL not like", value, "url");
			return (Criteria) this;
		}

		public Criteria andUrlIn(List<String> values) {
			addCriterion("URL in", values, "url");
			return (Criteria) this;
		}

		public Criteria andUrlNotIn(List<String> values) {
			addCriterion("URL not in", values, "url");
			return (Criteria) this;
		}

		public Criteria andUrlBetween(String value1, String value2) {
			addCriterion("URL between", value1, value2, "url");
			return (Criteria) this;
		}

		public Criteria andUrlNotBetween(String value1, String value2) {
			addCriterion("URL not between", value1, value2, "url");
			return (Criteria) this;
		}

		public Criteria andImageurlIsNull() {
			addCriterion("ImageURL is null");
			return (Criteria) this;
		}

		public Criteria andImageurlIsNotNull() {
			addCriterion("ImageURL is not null");
			return (Criteria) this;
		}

		public Criteria andImageurlEqualTo(String value) {
			addCriterion("ImageURL =", value, "imageurl");
			return (Criteria) this;
		}

		public Criteria andImageurlNotEqualTo(String value) {
			addCriterion("ImageURL <>", value, "imageurl");
			return (Criteria) this;
		}

		public Criteria andImageurlGreaterThan(String value) {
			addCriterion("ImageURL >", value, "imageurl");
			return (Criteria) this;
		}

		public Criteria andImageurlGreaterThanOrEqualTo(String value) {
			addCriterion("ImageURL >=", value, "imageurl");
			return (Criteria) this;
		}

		public Criteria andImageurlLessThan(String value) {
			addCriterion("ImageURL <", value, "imageurl");
			return (Criteria) this;
		}

		public Criteria andImageurlLessThanOrEqualTo(String value) {
			addCriterion("ImageURL <=", value, "imageurl");
			return (Criteria) this;
		}

		public Criteria andImageurlLike(String value) {
			addCriterion("ImageURL like", value, "imageurl");
			return (Criteria) this;
		}

		public Criteria andImageurlNotLike(String value) {
			addCriterion("ImageURL not like", value, "imageurl");
			return (Criteria) this;
		}

		public Criteria andImageurlIn(List<String> values) {
			addCriterion("ImageURL in", values, "imageurl");
			return (Criteria) this;
		}

		public Criteria andImageurlNotIn(List<String> values) {
			addCriterion("ImageURL not in", values, "imageurl");
			return (Criteria) this;
		}

		public Criteria andImageurlBetween(String value1, String value2) {
			addCriterion("ImageURL between", value1, value2, "imageurl");
			return (Criteria) this;
		}

		public Criteria andImageurlNotBetween(String value1, String value2) {
			addCriterion("ImageURL not between", value1, value2, "imageurl");
			return (Criteria) this;
		}

		public Criteria andAllowcommentIsNull() {
			addCriterion("AllowComment is null");
			return (Criteria) this;
		}

		public Criteria andAllowcommentIsNotNull() {
			addCriterion("AllowComment is not null");
			return (Criteria) this;
		}

		public Criteria andAllowcommentEqualTo(Boolean value) {
			addCriterion("AllowComment =", value, "allowcomment");
			return (Criteria) this;
		}

		public Criteria andAllowcommentNotEqualTo(Boolean value) {
			addCriterion("AllowComment <>", value, "allowcomment");
			return (Criteria) this;
		}

		public Criteria andAllowcommentGreaterThan(Boolean value) {
			addCriterion("AllowComment >", value, "allowcomment");
			return (Criteria) this;
		}

		public Criteria andAllowcommentGreaterThanOrEqualTo(Boolean value) {
			addCriterion("AllowComment >=", value, "allowcomment");
			return (Criteria) this;
		}

		public Criteria andAllowcommentLessThan(Boolean value) {
			addCriterion("AllowComment <", value, "allowcomment");
			return (Criteria) this;
		}

		public Criteria andAllowcommentLessThanOrEqualTo(Boolean value) {
			addCriterion("AllowComment <=", value, "allowcomment");
			return (Criteria) this;
		}

		public Criteria andAllowcommentIn(List<Boolean> values) {
			addCriterion("AllowComment in", values, "allowcomment");
			return (Criteria) this;
		}

		public Criteria andAllowcommentNotIn(List<Boolean> values) {
			addCriterion("AllowComment not in", values, "allowcomment");
			return (Criteria) this;
		}

		public Criteria andAllowcommentBetween(Boolean value1, Boolean value2) {
			addCriterion("AllowComment between", value1, value2, "allowcomment");
			return (Criteria) this;
		}

		public Criteria andAllowcommentNotBetween(Boolean value1, Boolean value2) {
			addCriterion("AllowComment not between", value1, value2,
					"allowcomment");
			return (Criteria) this;
		}

		public Criteria andIspublicIsNull() {
			addCriterion("IsPublic is null");
			return (Criteria) this;
		}

		public Criteria andIspublicIsNotNull() {
			addCriterion("IsPublic is not null");
			return (Criteria) this;
		}

		public Criteria andIspublicEqualTo(Boolean value) {
			addCriterion("IsPublic =", value, "ispublic");
			return (Criteria) this;
		}

		public Criteria andIspublicNotEqualTo(Boolean value) {
			addCriterion("IsPublic <>", value, "ispublic");
			return (Criteria) this;
		}

		public Criteria andIspublicGreaterThan(Boolean value) {
			addCriterion("IsPublic >", value, "ispublic");
			return (Criteria) this;
		}

		public Criteria andIspublicGreaterThanOrEqualTo(Boolean value) {
			addCriterion("IsPublic >=", value, "ispublic");
			return (Criteria) this;
		}

		public Criteria andIspublicLessThan(Boolean value) {
			addCriterion("IsPublic <", value, "ispublic");
			return (Criteria) this;
		}

		public Criteria andIspublicLessThanOrEqualTo(Boolean value) {
			addCriterion("IsPublic <=", value, "ispublic");
			return (Criteria) this;
		}

		public Criteria andIspublicIn(List<Boolean> values) {
			addCriterion("IsPublic in", values, "ispublic");
			return (Criteria) this;
		}

		public Criteria andIspublicNotIn(List<Boolean> values) {
			addCriterion("IsPublic not in", values, "ispublic");
			return (Criteria) this;
		}

		public Criteria andIspublicBetween(Boolean value1, Boolean value2) {
			addCriterion("IsPublic between", value1, value2, "ispublic");
			return (Criteria) this;
		}

		public Criteria andIspublicNotBetween(Boolean value1, Boolean value2) {
			addCriterion("IsPublic not between", value1, value2, "ispublic");
			return (Criteria) this;
		}

		public Criteria andIsdeletedIsNull() {
			addCriterion("IsDeleted is null");
			return (Criteria) this;
		}

		public Criteria andIsdeletedIsNotNull() {
			addCriterion("IsDeleted is not null");
			return (Criteria) this;
		}

		public Criteria andIsdeletedEqualTo(Boolean value) {
			addCriterion("IsDeleted =", value, "isdeleted");
			return (Criteria) this;
		}

		public Criteria andIsdeletedNotEqualTo(Boolean value) {
			addCriterion("IsDeleted <>", value, "isdeleted");
			return (Criteria) this;
		}

		public Criteria andIsdeletedGreaterThan(Boolean value) {
			addCriterion("IsDeleted >", value, "isdeleted");
			return (Criteria) this;
		}

		public Criteria andIsdeletedGreaterThanOrEqualTo(Boolean value) {
			addCriterion("IsDeleted >=", value, "isdeleted");
			return (Criteria) this;
		}

		public Criteria andIsdeletedLessThan(Boolean value) {
			addCriterion("IsDeleted <", value, "isdeleted");
			return (Criteria) this;
		}

		public Criteria andIsdeletedLessThanOrEqualTo(Boolean value) {
			addCriterion("IsDeleted <=", value, "isdeleted");
			return (Criteria) this;
		}

		public Criteria andIsdeletedIn(List<Boolean> values) {
			addCriterion("IsDeleted in", values, "isdeleted");
			return (Criteria) this;
		}

		public Criteria andIsdeletedNotIn(List<Boolean> values) {
			addCriterion("IsDeleted not in", values, "isdeleted");
			return (Criteria) this;
		}

		public Criteria andIsdeletedBetween(Boolean value1, Boolean value2) {
			addCriterion("IsDeleted between", value1, value2, "isdeleted");
			return (Criteria) this;
		}

		public Criteria andIsdeletedNotBetween(Boolean value1, Boolean value2) {
			addCriterion("IsDeleted not between", value1, value2, "isdeleted");
			return (Criteria) this;
		}

		public Criteria andForwardidfkIsNull() {
			addCriterion("ForwardIDFK is null");
			return (Criteria) this;
		}

		public Criteria andForwardidfkIsNotNull() {
			addCriterion("ForwardIDFK is not null");
			return (Criteria) this;
		}

		public Criteria andForwardidfkEqualTo(String value) {
			addCriterion("ForwardIDFK =", value, "forwardidfk");
			return (Criteria) this;
		}

		public Criteria andForwardidfkNotEqualTo(String value) {
			addCriterion("ForwardIDFK <>", value, "forwardidfk");
			return (Criteria) this;
		}

		public Criteria andForwardidfkGreaterThan(String value) {
			addCriterion("ForwardIDFK >", value, "forwardidfk");
			return (Criteria) this;
		}

		public Criteria andForwardidfkGreaterThanOrEqualTo(String value) {
			addCriterion("ForwardIDFK >=", value, "forwardidfk");
			return (Criteria) this;
		}

		public Criteria andForwardidfkLessThan(String value) {
			addCriterion("ForwardIDFK <", value, "forwardidfk");
			return (Criteria) this;
		}

		public Criteria andForwardidfkLessThanOrEqualTo(String value) {
			addCriterion("ForwardIDFK <=", value, "forwardidfk");
			return (Criteria) this;
		}

		public Criteria andForwardidfkLike(String value) {
			addCriterion("ForwardIDFK like", value, "forwardidfk");
			return (Criteria) this;
		}

		public Criteria andForwardidfkNotLike(String value) {
			addCriterion("ForwardIDFK not like", value, "forwardidfk");
			return (Criteria) this;
		}

		public Criteria andForwardidfkIn(List<String> values) {
			addCriterion("ForwardIDFK in", values, "forwardidfk");
			return (Criteria) this;
		}

		public Criteria andForwardidfkNotIn(List<String> values) {
			addCriterion("ForwardIDFK not in", values, "forwardidfk");
			return (Criteria) this;
		}

		public Criteria andForwardidfkBetween(String value1, String value2) {
			addCriterion("ForwardIDFK between", value1, value2, "forwardidfk");
			return (Criteria) this;
		}

		public Criteria andForwardidfkNotBetween(String value1, String value2) {
			addCriterion("ForwardIDFK not between", value1, value2,
					"forwardidfk");
			return (Criteria) this;
		}

		public Criteria andCreateddateIsNull() {
			addCriterion("CreatedDate is null");
			return (Criteria) this;
		}

		public Criteria andCreateddateIsNotNull() {
			addCriterion("CreatedDate is not null");
			return (Criteria) this;
		}

		public Criteria andCreateddateEqualTo(Date value) {
			addCriterion("CreatedDate =", value, "createddate");
			return (Criteria) this;
		}

		public Criteria andCreateddateNotEqualTo(Date value) {
			addCriterion("CreatedDate <>", value, "createddate");
			return (Criteria) this;
		}

		public Criteria andCreateddateGreaterThan(Date value) {
			addCriterion("CreatedDate >", value, "createddate");
			return (Criteria) this;
		}

		public Criteria andCreateddateGreaterThanOrEqualTo(Date value) {
			addCriterion("CreatedDate >=", value, "createddate");
			return (Criteria) this;
		}

		public Criteria andCreateddateLessThan(Date value) {
			addCriterion("CreatedDate <", value, "createddate");
			return (Criteria) this;
		}

		public Criteria andCreateddateLessThanOrEqualTo(Date value) {
			addCriterion("CreatedDate <=", value, "createddate");
			return (Criteria) this;
		}

		public Criteria andCreateddateIn(List<Date> values) {
			addCriterion("CreatedDate in", values, "createddate");
			return (Criteria) this;
		}

		public Criteria andCreateddateNotIn(List<Date> values) {
			addCriterion("CreatedDate not in", values, "createddate");
			return (Criteria) this;
		}

		public Criteria andCreateddateBetween(Date value1, Date value2) {
			addCriterion("CreatedDate between", value1, value2, "createddate");
			return (Criteria) this;
		}

		public Criteria andCreateddateNotBetween(Date value1, Date value2) {
			addCriterion("CreatedDate not between", value1, value2,
					"createddate");
			return (Criteria) this;
		}

		public Criteria andModifieddateIsNull() {
			addCriterion("ModifiedDate is null");
			return (Criteria) this;
		}

		public Criteria andModifieddateIsNotNull() {
			addCriterion("ModifiedDate is not null");
			return (Criteria) this;
		}

		public Criteria andModifieddateEqualTo(Date value) {
			addCriterion("ModifiedDate =", value, "modifieddate");
			return (Criteria) this;
		}

		public Criteria andModifieddateNotEqualTo(Date value) {
			addCriterion("ModifiedDate <>", value, "modifieddate");
			return (Criteria) this;
		}

		public Criteria andModifieddateGreaterThan(Date value) {
			addCriterion("ModifiedDate >", value, "modifieddate");
			return (Criteria) this;
		}

		public Criteria andModifieddateGreaterThanOrEqualTo(Date value) {
			addCriterion("ModifiedDate >=", value, "modifieddate");
			return (Criteria) this;
		}

		public Criteria andModifieddateLessThan(Date value) {
			addCriterion("ModifiedDate <", value, "modifieddate");
			return (Criteria) this;
		}

		public Criteria andModifieddateLessThanOrEqualTo(Date value) {
			addCriterion("ModifiedDate <=", value, "modifieddate");
			return (Criteria) this;
		}

		public Criteria andModifieddateIn(List<Date> values) {
			addCriterion("ModifiedDate in", values, "modifieddate");
			return (Criteria) this;
		}

		public Criteria andModifieddateNotIn(List<Date> values) {
			addCriterion("ModifiedDate not in", values, "modifieddate");
			return (Criteria) this;
		}

		public Criteria andModifieddateBetween(Date value1, Date value2) {
			addCriterion("ModifiedDate between", value1, value2, "modifieddate");
			return (Criteria) this;
		}

		public Criteria andModifieddateNotBetween(Date value1, Date value2) {
			addCriterion("ModifiedDate not between", value1, value2,
					"modifieddate");
			return (Criteria) this;
		}

		public Criteria andCommentcountIsNull() {
			addCriterion("CommentCount is null");
			return (Criteria) this;
		}

		public Criteria andCommentcountIsNotNull() {
			addCriterion("CommentCount is not null");
			return (Criteria) this;
		}

		public Criteria andCommentcountEqualTo(Integer value) {
			addCriterion("CommentCount =", value, "commentcount");
			return (Criteria) this;
		}

		public Criteria andCommentcountNotEqualTo(Integer value) {
			addCriterion("CommentCount <>", value, "commentcount");
			return (Criteria) this;
		}

		public Criteria andCommentcountGreaterThan(Integer value) {
			addCriterion("CommentCount >", value, "commentcount");
			return (Criteria) this;
		}

		public Criteria andCommentcountGreaterThanOrEqualTo(Integer value) {
			addCriterion("CommentCount >=", value, "commentcount");
			return (Criteria) this;
		}

		public Criteria andCommentcountLessThan(Integer value) {
			addCriterion("CommentCount <", value, "commentcount");
			return (Criteria) this;
		}

		public Criteria andCommentcountLessThanOrEqualTo(Integer value) {
			addCriterion("CommentCount <=", value, "commentcount");
			return (Criteria) this;
		}

		public Criteria andCommentcountIn(List<Integer> values) {
			addCriterion("CommentCount in", values, "commentcount");
			return (Criteria) this;
		}

		public Criteria andCommentcountNotIn(List<Integer> values) {
			addCriterion("CommentCount not in", values, "commentcount");
			return (Criteria) this;
		}

		public Criteria andCommentcountBetween(Integer value1, Integer value2) {
			addCriterion("CommentCount between", value1, value2, "commentcount");
			return (Criteria) this;
		}

		public Criteria andCommentcountNotBetween(Integer value1, Integer value2) {
			addCriterion("CommentCount not between", value1, value2,
					"commentcount");
			return (Criteria) this;
		}

		public Criteria andForwardcountIsNull() {
			addCriterion("ForwardCount is null");
			return (Criteria) this;
		}

		public Criteria andForwardcountIsNotNull() {
			addCriterion("ForwardCount is not null");
			return (Criteria) this;
		}

		public Criteria andForwardcountEqualTo(Integer value) {
			addCriterion("ForwardCount =", value, "forwardcount");
			return (Criteria) this;
		}

		public Criteria andForwardcountNotEqualTo(Integer value) {
			addCriterion("ForwardCount <>", value, "forwardcount");
			return (Criteria) this;
		}

		public Criteria andForwardcountGreaterThan(Integer value) {
			addCriterion("ForwardCount >", value, "forwardcount");
			return (Criteria) this;
		}

		public Criteria andForwardcountGreaterThanOrEqualTo(Integer value) {
			addCriterion("ForwardCount >=", value, "forwardcount");
			return (Criteria) this;
		}

		public Criteria andForwardcountLessThan(Integer value) {
			addCriterion("ForwardCount <", value, "forwardcount");
			return (Criteria) this;
		}

		public Criteria andForwardcountLessThanOrEqualTo(Integer value) {
			addCriterion("ForwardCount <=", value, "forwardcount");
			return (Criteria) this;
		}

		public Criteria andForwardcountIn(List<Integer> values) {
			addCriterion("ForwardCount in", values, "forwardcount");
			return (Criteria) this;
		}

		public Criteria andForwardcountNotIn(List<Integer> values) {
			addCriterion("ForwardCount not in", values, "forwardcount");
			return (Criteria) this;
		}

		public Criteria andForwardcountBetween(Integer value1, Integer value2) {
			addCriterion("ForwardCount between", value1, value2, "forwardcount");
			return (Criteria) this;
		}

		public Criteria andForwardcountNotBetween(Integer value1, Integer value2) {
			addCriterion("ForwardCount not between", value1, value2,
					"forwardcount");
			return (Criteria) this;
		}

		public Criteria andLikecountIsNull() {
			addCriterion("LikeCount is null");
			return (Criteria) this;
		}

		public Criteria andLikecountIsNotNull() {
			addCriterion("LikeCount is not null");
			return (Criteria) this;
		}

		public Criteria andLikecountEqualTo(Integer value) {
			addCriterion("LikeCount =", value, "likecount");
			return (Criteria) this;
		}

		public Criteria andLikecountNotEqualTo(Integer value) {
			addCriterion("LikeCount <>", value, "likecount");
			return (Criteria) this;
		}

		public Criteria andLikecountGreaterThan(Integer value) {
			addCriterion("LikeCount >", value, "likecount");
			return (Criteria) this;
		}

		public Criteria andLikecountGreaterThanOrEqualTo(Integer value) {
			addCriterion("LikeCount >=", value, "likecount");
			return (Criteria) this;
		}

		public Criteria andLikecountLessThan(Integer value) {
			addCriterion("LikeCount <", value, "likecount");
			return (Criteria) this;
		}

		public Criteria andLikecountLessThanOrEqualTo(Integer value) {
			addCriterion("LikeCount <=", value, "likecount");
			return (Criteria) this;
		}

		public Criteria andLikecountIn(List<Integer> values) {
			addCriterion("LikeCount in", values, "likecount");
			return (Criteria) this;
		}

		public Criteria andLikecountNotIn(List<Integer> values) {
			addCriterion("LikeCount not in", values, "likecount");
			return (Criteria) this;
		}

		public Criteria andLikecountBetween(Integer value1, Integer value2) {
			addCriterion("LikeCount between", value1, value2, "likecount");
			return (Criteria) this;
		}

		public Criteria andLikecountNotBetween(Integer value1, Integer value2) {
			addCriterion("LikeCount not between", value1, value2, "likecount");
			return (Criteria) this;
		}

		public Criteria andLevelIsNull() {
			addCriterion("Level is null");
			return (Criteria) this;
		}

		public Criteria andLevelIsNotNull() {
			addCriterion("Level is not null");
			return (Criteria) this;
		}

		public Criteria andLevelEqualTo(Integer value) {
			addCriterion("Level =", value, "level");
			return (Criteria) this;
		}

		public Criteria andLevelNotEqualTo(Integer value) {
			addCriterion("Level <>", value, "level");
			return (Criteria) this;
		}

		public Criteria andLevelGreaterThan(Integer value) {
			addCriterion("Level >", value, "level");
			return (Criteria) this;
		}

		public Criteria andLevelGreaterThanOrEqualTo(Integer value) {
			addCriterion("Level >=", value, "level");
			return (Criteria) this;
		}

		public Criteria andLevelLessThan(Integer value) {
			addCriterion("Level <", value, "level");
			return (Criteria) this;
		}

		public Criteria andLevelLessThanOrEqualTo(Integer value) {
			addCriterion("Level <=", value, "level");
			return (Criteria) this;
		}

		public Criteria andLevelIn(List<Integer> values) {
			addCriterion("Level in", values, "level");
			return (Criteria) this;
		}

		public Criteria andLevelNotIn(List<Integer> values) {
			addCriterion("Level not in", values, "level");
			return (Criteria) this;
		}

		public Criteria andLevelBetween(Integer value1, Integer value2) {
			addCriterion("Level between", value1, value2, "level");
			return (Criteria) this;
		}

		public Criteria andLevelNotBetween(Integer value1, Integer value2) {
			addCriterion("Level not between", value1, value2, "level");
			return (Criteria) this;
		}

		public Criteria andWeightIsNull() {
			addCriterion("Weight is null");
			return (Criteria) this;
		}

		public Criteria andWeightIsNotNull() {
			addCriterion("Weight is not null");
			return (Criteria) this;
		}

		public Criteria andWeightEqualTo(Integer value) {
			addCriterion("Weight =", value, "weight");
			return (Criteria) this;
		}

		public Criteria andWeightNotEqualTo(Integer value) {
			addCriterion("Weight <>", value, "weight");
			return (Criteria) this;
		}

		public Criteria andWeightGreaterThan(Integer value) {
			addCriterion("Weight >", value, "weight");
			return (Criteria) this;
		}

		public Criteria andWeightGreaterThanOrEqualTo(Integer value) {
			addCriterion("Weight >=", value, "weight");
			return (Criteria) this;
		}

		public Criteria andWeightLessThan(Integer value) {
			addCriterion("Weight <", value, "weight");
			return (Criteria) this;
		}

		public Criteria andWeightLessThanOrEqualTo(Integer value) {
			addCriterion("Weight <=", value, "weight");
			return (Criteria) this;
		}

		public Criteria andWeightIn(List<Integer> values) {
			addCriterion("Weight in", values, "weight");
			return (Criteria) this;
		}

		public Criteria andWeightNotIn(List<Integer> values) {
			addCriterion("Weight not in", values, "weight");
			return (Criteria) this;
		}

		public Criteria andWeightBetween(Integer value1, Integer value2) {
			addCriterion("Weight between", value1, value2, "weight");
			return (Criteria) this;
		}

		public Criteria andWeightNotBetween(Integer value1, Integer value2) {
			addCriterion("Weight not between", value1, value2, "weight");
			return (Criteria) this;
		}

		public Criteria andSortIsNull() {
			addCriterion("Sort is null");
			return (Criteria) this;
		}

		public Criteria andSortIsNotNull() {
			addCriterion("Sort is not null");
			return (Criteria) this;
		}

		public Criteria andSortEqualTo(Integer value) {
			addCriterion("Sort =", value, "sort");
			return (Criteria) this;
		}

		public Criteria andSortNotEqualTo(Integer value) {
			addCriterion("Sort <>", value, "sort");
			return (Criteria) this;
		}

		public Criteria andSortGreaterThan(Integer value) {
			addCriterion("Sort >", value, "sort");
			return (Criteria) this;
		}

		public Criteria andSortGreaterThanOrEqualTo(Integer value) {
			addCriterion("Sort >=", value, "sort");
			return (Criteria) this;
		}

		public Criteria andSortLessThan(Integer value) {
			addCriterion("Sort <", value, "sort");
			return (Criteria) this;
		}

		public Criteria andSortLessThanOrEqualTo(Integer value) {
			addCriterion("Sort <=", value, "sort");
			return (Criteria) this;
		}

		public Criteria andSortIn(List<Integer> values) {
			addCriterion("Sort in", values, "sort");
			return (Criteria) this;
		}

		public Criteria andSortNotIn(List<Integer> values) {
			addCriterion("Sort not in", values, "sort");
			return (Criteria) this;
		}

		public Criteria andSortBetween(Integer value1, Integer value2) {
			addCriterion("Sort between", value1, value2, "sort");
			return (Criteria) this;
		}

		public Criteria andSortNotBetween(Integer value1, Integer value2) {
			addCriterion("Sort not between", value1, value2, "sort");
			return (Criteria) this;
		}

		public Criteria andTitleIsNull() {
			addCriterion("Title is null");
			return (Criteria) this;
		}

		public Criteria andTitleIsNotNull() {
			addCriterion("Title is not null");
			return (Criteria) this;
		}

		public Criteria andTitleEqualTo(String value) {
			addCriterion("Title =", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleNotEqualTo(String value) {
			addCriterion("Title <>", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleGreaterThan(String value) {
			addCriterion("Title >", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleGreaterThanOrEqualTo(String value) {
			addCriterion("Title >=", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleLessThan(String value) {
			addCriterion("Title <", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleLessThanOrEqualTo(String value) {
			addCriterion("Title <=", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleLike(String value) {
			addCriterion("Title like", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleNotLike(String value) {
			addCriterion("Title not like", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleIn(List<String> values) {
			addCriterion("Title in", values, "title");
			return (Criteria) this;
		}

		public Criteria andTitleNotIn(List<String> values) {
			addCriterion("Title not in", values, "title");
			return (Criteria) this;
		}

		public Criteria andTitleBetween(String value1, String value2) {
			addCriterion("Title between", value1, value2, "title");
			return (Criteria) this;
		}

		public Criteria andTitleNotBetween(String value1, String value2) {
			addCriterion("Title not between", value1, value2, "title");
			return (Criteria) this;
		}

		public Criteria andReferrerIsNull() {
			addCriterion("Referrer is null");
			return (Criteria) this;
		}

		public Criteria andReferrerIsNotNull() {
			addCriterion("Referrer is not null");
			return (Criteria) this;
		}

		public Criteria andReferrerEqualTo(String value) {
			addCriterion("Referrer =", value, "referrer");
			return (Criteria) this;
		}

		public Criteria andReferrerNotEqualTo(String value) {
			addCriterion("Referrer <>", value, "referrer");
			return (Criteria) this;
		}

		public Criteria andReferrerGreaterThan(String value) {
			addCriterion("Referrer >", value, "referrer");
			return (Criteria) this;
		}

		public Criteria andReferrerGreaterThanOrEqualTo(String value) {
			addCriterion("Referrer >=", value, "referrer");
			return (Criteria) this;
		}

		public Criteria andReferrerLessThan(String value) {
			addCriterion("Referrer <", value, "referrer");
			return (Criteria) this;
		}

		public Criteria andReferrerLessThanOrEqualTo(String value) {
			addCriterion("Referrer <=", value, "referrer");
			return (Criteria) this;
		}

		public Criteria andReferrerLike(String value) {
			addCriterion("Referrer like", value, "referrer");
			return (Criteria) this;
		}

		public Criteria andReferrerNotLike(String value) {
			addCriterion("Referrer not like", value, "referrer");
			return (Criteria) this;
		}

		public Criteria andReferrerIn(List<String> values) {
			addCriterion("Referrer in", values, "referrer");
			return (Criteria) this;
		}

		public Criteria andReferrerNotIn(List<String> values) {
			addCriterion("Referrer not in", values, "referrer");
			return (Criteria) this;
		}

		public Criteria andReferrerBetween(String value1, String value2) {
			addCriterion("Referrer between", value1, value2, "referrer");
			return (Criteria) this;
		}

		public Criteria andReferrerNotBetween(String value1, String value2) {
			addCriterion("Referrer not between", value1, value2, "referrer");
			return (Criteria) this;
		}

		public Criteria andRemark1IsNull() {
			addCriterion("Remark1 is null");
			return (Criteria) this;
		}

		public Criteria andRemark1IsNotNull() {
			addCriterion("Remark1 is not null");
			return (Criteria) this;
		}

		public Criteria andRemark1EqualTo(String value) {
			addCriterion("Remark1 =", value, "remark1");
			return (Criteria) this;
		}

		public Criteria andRemark1NotEqualTo(String value) {
			addCriterion("Remark1 <>", value, "remark1");
			return (Criteria) this;
		}

		public Criteria andRemark1GreaterThan(String value) {
			addCriterion("Remark1 >", value, "remark1");
			return (Criteria) this;
		}

		public Criteria andRemark1GreaterThanOrEqualTo(String value) {
			addCriterion("Remark1 >=", value, "remark1");
			return (Criteria) this;
		}

		public Criteria andRemark1LessThan(String value) {
			addCriterion("Remark1 <", value, "remark1");
			return (Criteria) this;
		}

		public Criteria andRemark1LessThanOrEqualTo(String value) {
			addCriterion("Remark1 <=", value, "remark1");
			return (Criteria) this;
		}

		public Criteria andRemark1Like(String value) {
			addCriterion("Remark1 like", value, "remark1");
			return (Criteria) this;
		}

		public Criteria andRemark1NotLike(String value) {
			addCriterion("Remark1 not like", value, "remark1");
			return (Criteria) this;
		}

		public Criteria andRemark1In(List<String> values) {
			addCriterion("Remark1 in", values, "remark1");
			return (Criteria) this;
		}

		public Criteria andRemark1NotIn(List<String> values) {
			addCriterion("Remark1 not in", values, "remark1");
			return (Criteria) this;
		}

		public Criteria andRemark1Between(String value1, String value2) {
			addCriterion("Remark1 between", value1, value2, "remark1");
			return (Criteria) this;
		}

		public Criteria andRemark1NotBetween(String value1, String value2) {
			addCriterion("Remark1 not between", value1, value2, "remark1");
			return (Criteria) this;
		}

		public Criteria andRemark2IsNull() {
			addCriterion("Remark2 is null");
			return (Criteria) this;
		}

		public Criteria andRemark2IsNotNull() {
			addCriterion("Remark2 is not null");
			return (Criteria) this;
		}

		public Criteria andRemark2EqualTo(String value) {
			addCriterion("Remark2 =", value, "remark2");
			return (Criteria) this;
		}

		public Criteria andRemark2NotEqualTo(String value) {
			addCriterion("Remark2 <>", value, "remark2");
			return (Criteria) this;
		}

		public Criteria andRemark2GreaterThan(String value) {
			addCriterion("Remark2 >", value, "remark2");
			return (Criteria) this;
		}

		public Criteria andRemark2GreaterThanOrEqualTo(String value) {
			addCriterion("Remark2 >=", value, "remark2");
			return (Criteria) this;
		}

		public Criteria andRemark2LessThan(String value) {
			addCriterion("Remark2 <", value, "remark2");
			return (Criteria) this;
		}

		public Criteria andRemark2LessThanOrEqualTo(String value) {
			addCriterion("Remark2 <=", value, "remark2");
			return (Criteria) this;
		}

		public Criteria andRemark2Like(String value) {
			addCriterion("Remark2 like", value, "remark2");
			return (Criteria) this;
		}

		public Criteria andRemark2NotLike(String value) {
			addCriterion("Remark2 not like", value, "remark2");
			return (Criteria) this;
		}

		public Criteria andRemark2In(List<String> values) {
			addCriterion("Remark2 in", values, "remark2");
			return (Criteria) this;
		}

		public Criteria andRemark2NotIn(List<String> values) {
			addCriterion("Remark2 not in", values, "remark2");
			return (Criteria) this;
		}

		public Criteria andRemark2Between(String value1, String value2) {
			addCriterion("Remark2 between", value1, value2, "remark2");
			return (Criteria) this;
		}

		public Criteria andRemark2NotBetween(String value1, String value2) {
			addCriterion("Remark2 not between", value1, value2, "remark2");
			return (Criteria) this;
		}

		public Criteria andRemark3IsNull() {
			addCriterion("Remark3 is null");
			return (Criteria) this;
		}

		public Criteria andRemark3IsNotNull() {
			addCriterion("Remark3 is not null");
			return (Criteria) this;
		}

		public Criteria andRemark3EqualTo(String value) {
			addCriterion("Remark3 =", value, "remark3");
			return (Criteria) this;
		}

		public Criteria andRemark3NotEqualTo(String value) {
			addCriterion("Remark3 <>", value, "remark3");
			return (Criteria) this;
		}

		public Criteria andRemark3GreaterThan(String value) {
			addCriterion("Remark3 >", value, "remark3");
			return (Criteria) this;
		}

		public Criteria andRemark3GreaterThanOrEqualTo(String value) {
			addCriterion("Remark3 >=", value, "remark3");
			return (Criteria) this;
		}

		public Criteria andRemark3LessThan(String value) {
			addCriterion("Remark3 <", value, "remark3");
			return (Criteria) this;
		}

		public Criteria andRemark3LessThanOrEqualTo(String value) {
			addCriterion("Remark3 <=", value, "remark3");
			return (Criteria) this;
		}

		public Criteria andRemark3Like(String value) {
			addCriterion("Remark3 like", value, "remark3");
			return (Criteria) this;
		}

		public Criteria andRemark3NotLike(String value) {
			addCriterion("Remark3 not like", value, "remark3");
			return (Criteria) this;
		}

		public Criteria andRemark3In(List<String> values) {
			addCriterion("Remark3 in", values, "remark3");
			return (Criteria) this;
		}

		public Criteria andRemark3NotIn(List<String> values) {
			addCriterion("Remark3 not in", values, "remark3");
			return (Criteria) this;
		}

		public Criteria andRemark3Between(String value1, String value2) {
			addCriterion("Remark3 between", value1, value2, "remark3");
			return (Criteria) this;
		}

		public Criteria andRemark3NotBetween(String value1, String value2) {
			addCriterion("Remark3 not between", value1, value2, "remark3");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table tb_feed
	 * @mbggenerated  Tue Dec 31 16:48:21 CST 2013
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_feed
     *
     * @mbggenerated do_not_delete_during_merge Mon Nov 25 11:34:32 CST 2013
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}