package com.dandelion.memberapp.model.po;

import java.util.ArrayList;
import java.util.List;

public class FriendExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table tb_friend
	 * @mbggenerated  Thu Jan 16 19:58:43 CST 2014
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table tb_friend
	 * @mbggenerated  Thu Jan 16 19:58:43 CST 2014
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table tb_friend
	 * @mbggenerated  Thu Jan 16 19:58:43 CST 2014
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_friend
	 * @mbggenerated  Thu Jan 16 19:58:43 CST 2014
	 */
	public FriendExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_friend
	 * @mbggenerated  Thu Jan 16 19:58:43 CST 2014
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_friend
	 * @mbggenerated  Thu Jan 16 19:58:43 CST 2014
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_friend
	 * @mbggenerated  Thu Jan 16 19:58:43 CST 2014
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_friend
	 * @mbggenerated  Thu Jan 16 19:58:43 CST 2014
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_friend
	 * @mbggenerated  Thu Jan 16 19:58:43 CST 2014
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_friend
	 * @mbggenerated  Thu Jan 16 19:58:43 CST 2014
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_friend
	 * @mbggenerated  Thu Jan 16 19:58:43 CST 2014
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_friend
	 * @mbggenerated  Thu Jan 16 19:58:43 CST 2014
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_friend
	 * @mbggenerated  Thu Jan 16 19:58:43 CST 2014
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_friend
	 * @mbggenerated  Thu Jan 16 19:58:43 CST 2014
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table tb_friend
	 * @mbggenerated  Thu Jan 16 19:58:43 CST 2014
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("ID is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("ID is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Long value) {
			addCriterion("ID =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Long value) {
			addCriterion("ID <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Long value) {
			addCriterion("ID >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Long value) {
			addCriterion("ID >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Long value) {
			addCriterion("ID <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Long value) {
			addCriterion("ID <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Long> values) {
			addCriterion("ID in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Long> values) {
			addCriterion("ID not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Long value1, Long value2) {
			addCriterion("ID between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Long value1, Long value2) {
			addCriterion("ID not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andFromuseridfkIsNull() {
			addCriterion("fromUserIDFK is null");
			return (Criteria) this;
		}

		public Criteria andFromuseridfkIsNotNull() {
			addCriterion("fromUserIDFK is not null");
			return (Criteria) this;
		}

		public Criteria andFromuseridfkEqualTo(Long value) {
			addCriterion("fromUserIDFK =", value, "fromuseridfk");
			return (Criteria) this;
		}

		public Criteria andFromuseridfkNotEqualTo(Long value) {
			addCriterion("fromUserIDFK <>", value, "fromuseridfk");
			return (Criteria) this;
		}

		public Criteria andFromuseridfkGreaterThan(Long value) {
			addCriterion("fromUserIDFK >", value, "fromuseridfk");
			return (Criteria) this;
		}

		public Criteria andFromuseridfkGreaterThanOrEqualTo(Long value) {
			addCriterion("fromUserIDFK >=", value, "fromuseridfk");
			return (Criteria) this;
		}

		public Criteria andFromuseridfkLessThan(Long value) {
			addCriterion("fromUserIDFK <", value, "fromuseridfk");
			return (Criteria) this;
		}

		public Criteria andFromuseridfkLessThanOrEqualTo(Long value) {
			addCriterion("fromUserIDFK <=", value, "fromuseridfk");
			return (Criteria) this;
		}

		public Criteria andFromuseridfkIn(List<Long> values) {
			addCriterion("fromUserIDFK in", values, "fromuseridfk");
			return (Criteria) this;
		}

		public Criteria andFromuseridfkNotIn(List<Long> values) {
			addCriterion("fromUserIDFK not in", values, "fromuseridfk");
			return (Criteria) this;
		}

		public Criteria andFromuseridfkBetween(Long value1, Long value2) {
			addCriterion("fromUserIDFK between", value1, value2, "fromuseridfk");
			return (Criteria) this;
		}

		public Criteria andFromuseridfkNotBetween(Long value1, Long value2) {
			addCriterion("fromUserIDFK not between", value1, value2,
					"fromuseridfk");
			return (Criteria) this;
		}

		public Criteria andTargetuseridfkIsNull() {
			addCriterion("targetUserIDFK is null");
			return (Criteria) this;
		}

		public Criteria andTargetuseridfkIsNotNull() {
			addCriterion("targetUserIDFK is not null");
			return (Criteria) this;
		}

		public Criteria andTargetuseridfkEqualTo(Long value) {
			addCriterion("targetUserIDFK =", value, "targetuseridfk");
			return (Criteria) this;
		}

		public Criteria andTargetuseridfkNotEqualTo(Long value) {
			addCriterion("targetUserIDFK <>", value, "targetuseridfk");
			return (Criteria) this;
		}

		public Criteria andTargetuseridfkGreaterThan(Long value) {
			addCriterion("targetUserIDFK >", value, "targetuseridfk");
			return (Criteria) this;
		}

		public Criteria andTargetuseridfkGreaterThanOrEqualTo(Long value) {
			addCriterion("targetUserIDFK >=", value, "targetuseridfk");
			return (Criteria) this;
		}

		public Criteria andTargetuseridfkLessThan(Long value) {
			addCriterion("targetUserIDFK <", value, "targetuseridfk");
			return (Criteria) this;
		}

		public Criteria andTargetuseridfkLessThanOrEqualTo(Long value) {
			addCriterion("targetUserIDFK <=", value, "targetuseridfk");
			return (Criteria) this;
		}

		public Criteria andTargetuseridfkIn(List<Long> values) {
			addCriterion("targetUserIDFK in", values, "targetuseridfk");
			return (Criteria) this;
		}

		public Criteria andTargetuseridfkNotIn(List<Long> values) {
			addCriterion("targetUserIDFK not in", values, "targetuseridfk");
			return (Criteria) this;
		}

		public Criteria andTargetuseridfkBetween(Long value1, Long value2) {
			addCriterion("targetUserIDFK between", value1, value2,
					"targetuseridfk");
			return (Criteria) this;
		}

		public Criteria andTargetuseridfkNotBetween(Long value1, Long value2) {
			addCriterion("targetUserIDFK not between", value1, value2,
					"targetuseridfk");
			return (Criteria) this;
		}

		public Criteria andIsmemberIsNull() {
			addCriterion("isMember is null");
			return (Criteria) this;
		}

		public Criteria andIsmemberIsNotNull() {
			addCriterion("isMember is not null");
			return (Criteria) this;
		}

		public Criteria andIsmemberEqualTo(Boolean value) {
			addCriterion("isMember =", value, "ismember");
			return (Criteria) this;
		}

		public Criteria andIsmemberNotEqualTo(Boolean value) {
			addCriterion("isMember <>", value, "ismember");
			return (Criteria) this;
		}

		public Criteria andIsmemberGreaterThan(Boolean value) {
			addCriterion("isMember >", value, "ismember");
			return (Criteria) this;
		}

		public Criteria andIsmemberGreaterThanOrEqualTo(Boolean value) {
			addCriterion("isMember >=", value, "ismember");
			return (Criteria) this;
		}

		public Criteria andIsmemberLessThan(Boolean value) {
			addCriterion("isMember <", value, "ismember");
			return (Criteria) this;
		}

		public Criteria andIsmemberLessThanOrEqualTo(Boolean value) {
			addCriterion("isMember <=", value, "ismember");
			return (Criteria) this;
		}

		public Criteria andIsmemberIn(List<Boolean> values) {
			addCriterion("isMember in", values, "ismember");
			return (Criteria) this;
		}

		public Criteria andIsmemberNotIn(List<Boolean> values) {
			addCriterion("isMember not in", values, "ismember");
			return (Criteria) this;
		}

		public Criteria andIsmemberBetween(Boolean value1, Boolean value2) {
			addCriterion("isMember between", value1, value2, "ismember");
			return (Criteria) this;
		}

		public Criteria andIsmemberNotBetween(Boolean value1, Boolean value2) {
			addCriterion("isMember not between", value1, value2, "ismember");
			return (Criteria) this;
		}

		public Criteria andAmountIsNull() {
			addCriterion("amount is null");
			return (Criteria) this;
		}

		public Criteria andAmountIsNotNull() {
			addCriterion("amount is not null");
			return (Criteria) this;
		}

		public Criteria andAmountEqualTo(Long value) {
			addCriterion("amount =", value, "amount");
			return (Criteria) this;
		}

		public Criteria andAmountNotEqualTo(Long value) {
			addCriterion("amount <>", value, "amount");
			return (Criteria) this;
		}

		public Criteria andAmountGreaterThan(Long value) {
			addCriterion("amount >", value, "amount");
			return (Criteria) this;
		}

		public Criteria andAmountGreaterThanOrEqualTo(Long value) {
			addCriterion("amount >=", value, "amount");
			return (Criteria) this;
		}

		public Criteria andAmountLessThan(Long value) {
			addCriterion("amount <", value, "amount");
			return (Criteria) this;
		}

		public Criteria andAmountLessThanOrEqualTo(Long value) {
			addCriterion("amount <=", value, "amount");
			return (Criteria) this;
		}

		public Criteria andAmountIn(List<Long> values) {
			addCriterion("amount in", values, "amount");
			return (Criteria) this;
		}

		public Criteria andAmountNotIn(List<Long> values) {
			addCriterion("amount not in", values, "amount");
			return (Criteria) this;
		}

		public Criteria andAmountBetween(Long value1, Long value2) {
			addCriterion("amount between", value1, value2, "amount");
			return (Criteria) this;
		}

		public Criteria andAmountNotBetween(Long value1, Long value2) {
			addCriterion("amount not between", value1, value2, "amount");
			return (Criteria) this;
		}

		public Criteria andAmountcountIsNull() {
			addCriterion("amountCount is null");
			return (Criteria) this;
		}

		public Criteria andAmountcountIsNotNull() {
			addCriterion("amountCount is not null");
			return (Criteria) this;
		}

		public Criteria andAmountcountEqualTo(Long value) {
			addCriterion("amountCount =", value, "amountcount");
			return (Criteria) this;
		}

		public Criteria andAmountcountNotEqualTo(Long value) {
			addCriterion("amountCount <>", value, "amountcount");
			return (Criteria) this;
		}

		public Criteria andAmountcountGreaterThan(Long value) {
			addCriterion("amountCount >", value, "amountcount");
			return (Criteria) this;
		}

		public Criteria andAmountcountGreaterThanOrEqualTo(Long value) {
			addCriterion("amountCount >=", value, "amountcount");
			return (Criteria) this;
		}

		public Criteria andAmountcountLessThan(Long value) {
			addCriterion("amountCount <", value, "amountcount");
			return (Criteria) this;
		}

		public Criteria andAmountcountLessThanOrEqualTo(Long value) {
			addCriterion("amountCount <=", value, "amountcount");
			return (Criteria) this;
		}

		public Criteria andAmountcountIn(List<Long> values) {
			addCriterion("amountCount in", values, "amountcount");
			return (Criteria) this;
		}

		public Criteria andAmountcountNotIn(List<Long> values) {
			addCriterion("amountCount not in", values, "amountcount");
			return (Criteria) this;
		}

		public Criteria andAmountcountBetween(Long value1, Long value2) {
			addCriterion("amountCount between", value1, value2, "amountcount");
			return (Criteria) this;
		}

		public Criteria andAmountcountNotBetween(Long value1, Long value2) {
			addCriterion("amountCount not between", value1, value2,
					"amountcount");
			return (Criteria) this;
		}

		public Criteria andScoreIsNull() {
			addCriterion("score is null");
			return (Criteria) this;
		}

		public Criteria andScoreIsNotNull() {
			addCriterion("score is not null");
			return (Criteria) this;
		}

		public Criteria andScoreEqualTo(Long value) {
			addCriterion("score =", value, "score");
			return (Criteria) this;
		}

		public Criteria andScoreNotEqualTo(Long value) {
			addCriterion("score <>", value, "score");
			return (Criteria) this;
		}

		public Criteria andScoreGreaterThan(Long value) {
			addCriterion("score >", value, "score");
			return (Criteria) this;
		}

		public Criteria andScoreGreaterThanOrEqualTo(Long value) {
			addCriterion("score >=", value, "score");
			return (Criteria) this;
		}

		public Criteria andScoreLessThan(Long value) {
			addCriterion("score <", value, "score");
			return (Criteria) this;
		}

		public Criteria andScoreLessThanOrEqualTo(Long value) {
			addCriterion("score <=", value, "score");
			return (Criteria) this;
		}

		public Criteria andScoreIn(List<Long> values) {
			addCriterion("score in", values, "score");
			return (Criteria) this;
		}

		public Criteria andScoreNotIn(List<Long> values) {
			addCriterion("score not in", values, "score");
			return (Criteria) this;
		}

		public Criteria andScoreBetween(Long value1, Long value2) {
			addCriterion("score between", value1, value2, "score");
			return (Criteria) this;
		}

		public Criteria andScoreNotBetween(Long value1, Long value2) {
			addCriterion("score not between", value1, value2, "score");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table tb_friend
	 * @mbggenerated  Thu Jan 16 19:58:43 CST 2014
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_friend
     *
     * @mbggenerated do_not_delete_during_merge Sun Nov 24 23:38:35 CST 2013
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}