package com.dandelion.memberapp.model.po;

public class Friend {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_friend.ID
	 * @mbggenerated  Thu Jan 16 19:58:43 CST 2014
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_friend.fromUserIDFK
	 * @mbggenerated  Thu Jan 16 19:58:43 CST 2014
	 */
	private Long fromuseridfk;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_friend.targetUserIDFK
	 * @mbggenerated  Thu Jan 16 19:58:43 CST 2014
	 */
	private Long targetuseridfk;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_friend.isMember
	 * @mbggenerated  Thu Jan 16 19:58:43 CST 2014
	 */
	private Boolean ismember;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_friend.amount
	 * @mbggenerated  Thu Jan 16 19:58:43 CST 2014
	 */
	private Long amount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_friend.amountCount
	 * @mbggenerated  Thu Jan 16 19:58:43 CST 2014
	 */
	private Long amountcount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_friend.score
	 * @mbggenerated  Thu Jan 16 19:58:43 CST 2014
	 */
	private Long score;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_friend.ID
	 * @return  the value of tb_friend.ID
	 * @mbggenerated  Thu Jan 16 19:58:43 CST 2014
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_friend.ID
	 * @param id  the value for tb_friend.ID
	 * @mbggenerated  Thu Jan 16 19:58:43 CST 2014
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_friend.fromUserIDFK
	 * @return  the value of tb_friend.fromUserIDFK
	 * @mbggenerated  Thu Jan 16 19:58:43 CST 2014
	 */
	public Long getFromuseridfk() {
		return fromuseridfk;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_friend.fromUserIDFK
	 * @param fromuseridfk  the value for tb_friend.fromUserIDFK
	 * @mbggenerated  Thu Jan 16 19:58:43 CST 2014
	 */
	public void setFromuseridfk(Long fromuseridfk) {
		this.fromuseridfk = fromuseridfk;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_friend.targetUserIDFK
	 * @return  the value of tb_friend.targetUserIDFK
	 * @mbggenerated  Thu Jan 16 19:58:43 CST 2014
	 */
	public Long getTargetuseridfk() {
		return targetuseridfk;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_friend.targetUserIDFK
	 * @param targetuseridfk  the value for tb_friend.targetUserIDFK
	 * @mbggenerated  Thu Jan 16 19:58:43 CST 2014
	 */
	public void setTargetuseridfk(Long targetuseridfk) {
		this.targetuseridfk = targetuseridfk;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_friend.isMember
	 * @return  the value of tb_friend.isMember
	 * @mbggenerated  Thu Jan 16 19:58:43 CST 2014
	 */
	public Boolean getIsmember() {
		return ismember;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_friend.isMember
	 * @param ismember  the value for tb_friend.isMember
	 * @mbggenerated  Thu Jan 16 19:58:43 CST 2014
	 */
	public void setIsmember(Boolean ismember) {
		this.ismember = ismember;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_friend.amount
	 * @return  the value of tb_friend.amount
	 * @mbggenerated  Thu Jan 16 19:58:43 CST 2014
	 */
	public Long getAmount() {
		return amount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_friend.amount
	 * @param amount  the value for tb_friend.amount
	 * @mbggenerated  Thu Jan 16 19:58:43 CST 2014
	 */
	public void setAmount(Long amount) {
		this.amount = amount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_friend.amountCount
	 * @return  the value of tb_friend.amountCount
	 * @mbggenerated  Thu Jan 16 19:58:43 CST 2014
	 */
	public Long getAmountcount() {
		return amountcount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_friend.amountCount
	 * @param amountcount  the value for tb_friend.amountCount
	 * @mbggenerated  Thu Jan 16 19:58:43 CST 2014
	 */
	public void setAmountcount(Long amountcount) {
		this.amountcount = amountcount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_friend.score
	 * @return  the value of tb_friend.score
	 * @mbggenerated  Thu Jan 16 19:58:43 CST 2014
	 */
	public Long getScore() {
		return score;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_friend.score
	 * @param score  the value for tb_friend.score
	 * @mbggenerated  Thu Jan 16 19:58:43 CST 2014
	 */
	public void setScore(Long score) {
		this.score = score;
	}
}