package com.dandelion.memberapp.model.po;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class MerchantExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table tb_merchant
	 * @mbggenerated  Tue Dec 31 16:48:21 CST 2013
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table tb_merchant
	 * @mbggenerated  Tue Dec 31 16:48:21 CST 2013
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table tb_merchant
	 * @mbggenerated  Tue Dec 31 16:48:21 CST 2013
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_merchant
	 * @mbggenerated  Tue Dec 31 16:48:21 CST 2013
	 */
	public MerchantExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_merchant
	 * @mbggenerated  Tue Dec 31 16:48:21 CST 2013
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_merchant
	 * @mbggenerated  Tue Dec 31 16:48:21 CST 2013
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_merchant
	 * @mbggenerated  Tue Dec 31 16:48:21 CST 2013
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_merchant
	 * @mbggenerated  Tue Dec 31 16:48:21 CST 2013
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_merchant
	 * @mbggenerated  Tue Dec 31 16:48:21 CST 2013
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_merchant
	 * @mbggenerated  Tue Dec 31 16:48:21 CST 2013
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_merchant
	 * @mbggenerated  Tue Dec 31 16:48:21 CST 2013
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_merchant
	 * @mbggenerated  Tue Dec 31 16:48:21 CST 2013
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_merchant
	 * @mbggenerated  Tue Dec 31 16:48:21 CST 2013
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_merchant
	 * @mbggenerated  Tue Dec 31 16:48:21 CST 2013
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table tb_merchant
	 * @mbggenerated  Tue Dec 31 16:48:21 CST 2013
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("ID is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("ID is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Long value) {
			addCriterion("ID =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Long value) {
			addCriterion("ID <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Long value) {
			addCriterion("ID >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Long value) {
			addCriterion("ID >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Long value) {
			addCriterion("ID <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Long value) {
			addCriterion("ID <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Long> values) {
			addCriterion("ID in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Long> values) {
			addCriterion("ID not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Long value1, Long value2) {
			addCriterion("ID between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Long value1, Long value2) {
			addCriterion("ID not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andAvatarurlIsNull() {
			addCriterion("AvatarUrl is null");
			return (Criteria) this;
		}

		public Criteria andAvatarurlIsNotNull() {
			addCriterion("AvatarUrl is not null");
			return (Criteria) this;
		}

		public Criteria andAvatarurlEqualTo(String value) {
			addCriterion("AvatarUrl =", value, "avatarurl");
			return (Criteria) this;
		}

		public Criteria andAvatarurlNotEqualTo(String value) {
			addCriterion("AvatarUrl <>", value, "avatarurl");
			return (Criteria) this;
		}

		public Criteria andAvatarurlGreaterThan(String value) {
			addCriterion("AvatarUrl >", value, "avatarurl");
			return (Criteria) this;
		}

		public Criteria andAvatarurlGreaterThanOrEqualTo(String value) {
			addCriterion("AvatarUrl >=", value, "avatarurl");
			return (Criteria) this;
		}

		public Criteria andAvatarurlLessThan(String value) {
			addCriterion("AvatarUrl <", value, "avatarurl");
			return (Criteria) this;
		}

		public Criteria andAvatarurlLessThanOrEqualTo(String value) {
			addCriterion("AvatarUrl <=", value, "avatarurl");
			return (Criteria) this;
		}

		public Criteria andAvatarurlLike(String value) {
			addCriterion("AvatarUrl like", value, "avatarurl");
			return (Criteria) this;
		}

		public Criteria andAvatarurlNotLike(String value) {
			addCriterion("AvatarUrl not like", value, "avatarurl");
			return (Criteria) this;
		}

		public Criteria andAvatarurlIn(List<String> values) {
			addCriterion("AvatarUrl in", values, "avatarurl");
			return (Criteria) this;
		}

		public Criteria andAvatarurlNotIn(List<String> values) {
			addCriterion("AvatarUrl not in", values, "avatarurl");
			return (Criteria) this;
		}

		public Criteria andAvatarurlBetween(String value1, String value2) {
			addCriterion("AvatarUrl between", value1, value2, "avatarurl");
			return (Criteria) this;
		}

		public Criteria andAvatarurlNotBetween(String value1, String value2) {
			addCriterion("AvatarUrl not between", value1, value2, "avatarurl");
			return (Criteria) this;
		}

		public Criteria andNameIsNull() {
			addCriterion("Name is null");
			return (Criteria) this;
		}

		public Criteria andNameIsNotNull() {
			addCriterion("Name is not null");
			return (Criteria) this;
		}

		public Criteria andNameEqualTo(String value) {
			addCriterion("Name =", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotEqualTo(String value) {
			addCriterion("Name <>", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameGreaterThan(String value) {
			addCriterion("Name >", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameGreaterThanOrEqualTo(String value) {
			addCriterion("Name >=", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLessThan(String value) {
			addCriterion("Name <", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLessThanOrEqualTo(String value) {
			addCriterion("Name <=", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLike(String value) {
			addCriterion("Name like", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotLike(String value) {
			addCriterion("Name not like", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameIn(List<String> values) {
			addCriterion("Name in", values, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotIn(List<String> values) {
			addCriterion("Name not in", values, "name");
			return (Criteria) this;
		}

		public Criteria andNameBetween(String value1, String value2) {
			addCriterion("Name between", value1, value2, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotBetween(String value1, String value2) {
			addCriterion("Name not between", value1, value2, "name");
			return (Criteria) this;
		}

		public Criteria andAddressIsNull() {
			addCriterion("Address is null");
			return (Criteria) this;
		}

		public Criteria andAddressIsNotNull() {
			addCriterion("Address is not null");
			return (Criteria) this;
		}

		public Criteria andAddressEqualTo(String value) {
			addCriterion("Address =", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressNotEqualTo(String value) {
			addCriterion("Address <>", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressGreaterThan(String value) {
			addCriterion("Address >", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressGreaterThanOrEqualTo(String value) {
			addCriterion("Address >=", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressLessThan(String value) {
			addCriterion("Address <", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressLessThanOrEqualTo(String value) {
			addCriterion("Address <=", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressLike(String value) {
			addCriterion("Address like", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressNotLike(String value) {
			addCriterion("Address not like", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressIn(List<String> values) {
			addCriterion("Address in", values, "address");
			return (Criteria) this;
		}

		public Criteria andAddressNotIn(List<String> values) {
			addCriterion("Address not in", values, "address");
			return (Criteria) this;
		}

		public Criteria andAddressBetween(String value1, String value2) {
			addCriterion("Address between", value1, value2, "address");
			return (Criteria) this;
		}

		public Criteria andAddressNotBetween(String value1, String value2) {
			addCriterion("Address not between", value1, value2, "address");
			return (Criteria) this;
		}

		public Criteria andPhoneIsNull() {
			addCriterion("Phone is null");
			return (Criteria) this;
		}

		public Criteria andPhoneIsNotNull() {
			addCriterion("Phone is not null");
			return (Criteria) this;
		}

		public Criteria andPhoneEqualTo(String value) {
			addCriterion("Phone =", value, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneNotEqualTo(String value) {
			addCriterion("Phone <>", value, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneGreaterThan(String value) {
			addCriterion("Phone >", value, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneGreaterThanOrEqualTo(String value) {
			addCriterion("Phone >=", value, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneLessThan(String value) {
			addCriterion("Phone <", value, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneLessThanOrEqualTo(String value) {
			addCriterion("Phone <=", value, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneLike(String value) {
			addCriterion("Phone like", value, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneNotLike(String value) {
			addCriterion("Phone not like", value, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneIn(List<String> values) {
			addCriterion("Phone in", values, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneNotIn(List<String> values) {
			addCriterion("Phone not in", values, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneBetween(String value1, String value2) {
			addCriterion("Phone between", value1, value2, "phone");
			return (Criteria) this;
		}

		public Criteria andPhoneNotBetween(String value1, String value2) {
			addCriterion("Phone not between", value1, value2, "phone");
			return (Criteria) this;
		}

		public Criteria andEmailIsNull() {
			addCriterion("Email is null");
			return (Criteria) this;
		}

		public Criteria andEmailIsNotNull() {
			addCriterion("Email is not null");
			return (Criteria) this;
		}

		public Criteria andEmailEqualTo(String value) {
			addCriterion("Email =", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailNotEqualTo(String value) {
			addCriterion("Email <>", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailGreaterThan(String value) {
			addCriterion("Email >", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailGreaterThanOrEqualTo(String value) {
			addCriterion("Email >=", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailLessThan(String value) {
			addCriterion("Email <", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailLessThanOrEqualTo(String value) {
			addCriterion("Email <=", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailLike(String value) {
			addCriterion("Email like", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailNotLike(String value) {
			addCriterion("Email not like", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailIn(List<String> values) {
			addCriterion("Email in", values, "email");
			return (Criteria) this;
		}

		public Criteria andEmailNotIn(List<String> values) {
			addCriterion("Email not in", values, "email");
			return (Criteria) this;
		}

		public Criteria andEmailBetween(String value1, String value2) {
			addCriterion("Email between", value1, value2, "email");
			return (Criteria) this;
		}

		public Criteria andEmailNotBetween(String value1, String value2) {
			addCriterion("Email not between", value1, value2, "email");
			return (Criteria) this;
		}

		public Criteria andMerchanttypeIsNull() {
			addCriterion("MerchantType is null");
			return (Criteria) this;
		}

		public Criteria andMerchanttypeIsNotNull() {
			addCriterion("MerchantType is not null");
			return (Criteria) this;
		}

		public Criteria andMerchanttypeEqualTo(String value) {
			addCriterion("MerchantType =", value, "merchanttype");
			return (Criteria) this;
		}

		public Criteria andMerchanttypeNotEqualTo(String value) {
			addCriterion("MerchantType <>", value, "merchanttype");
			return (Criteria) this;
		}

		public Criteria andMerchanttypeGreaterThan(String value) {
			addCriterion("MerchantType >", value, "merchanttype");
			return (Criteria) this;
		}

		public Criteria andMerchanttypeGreaterThanOrEqualTo(String value) {
			addCriterion("MerchantType >=", value, "merchanttype");
			return (Criteria) this;
		}

		public Criteria andMerchanttypeLessThan(String value) {
			addCriterion("MerchantType <", value, "merchanttype");
			return (Criteria) this;
		}

		public Criteria andMerchanttypeLessThanOrEqualTo(String value) {
			addCriterion("MerchantType <=", value, "merchanttype");
			return (Criteria) this;
		}

		public Criteria andMerchanttypeLike(String value) {
			addCriterion("MerchantType like", value, "merchanttype");
			return (Criteria) this;
		}

		public Criteria andMerchanttypeNotLike(String value) {
			addCriterion("MerchantType not like", value, "merchanttype");
			return (Criteria) this;
		}

		public Criteria andMerchanttypeIn(List<String> values) {
			addCriterion("MerchantType in", values, "merchanttype");
			return (Criteria) this;
		}

		public Criteria andMerchanttypeNotIn(List<String> values) {
			addCriterion("MerchantType not in", values, "merchanttype");
			return (Criteria) this;
		}

		public Criteria andMerchanttypeBetween(String value1, String value2) {
			addCriterion("MerchantType between", value1, value2, "merchanttype");
			return (Criteria) this;
		}

		public Criteria andMerchanttypeNotBetween(String value1, String value2) {
			addCriterion("MerchantType not between", value1, value2,
					"merchanttype");
			return (Criteria) this;
		}

		public Criteria andIntroductionIsNull() {
			addCriterion("Introduction is null");
			return (Criteria) this;
		}

		public Criteria andIntroductionIsNotNull() {
			addCriterion("Introduction is not null");
			return (Criteria) this;
		}

		public Criteria andIntroductionEqualTo(String value) {
			addCriterion("Introduction =", value, "introduction");
			return (Criteria) this;
		}

		public Criteria andIntroductionNotEqualTo(String value) {
			addCriterion("Introduction <>", value, "introduction");
			return (Criteria) this;
		}

		public Criteria andIntroductionGreaterThan(String value) {
			addCriterion("Introduction >", value, "introduction");
			return (Criteria) this;
		}

		public Criteria andIntroductionGreaterThanOrEqualTo(String value) {
			addCriterion("Introduction >=", value, "introduction");
			return (Criteria) this;
		}

		public Criteria andIntroductionLessThan(String value) {
			addCriterion("Introduction <", value, "introduction");
			return (Criteria) this;
		}

		public Criteria andIntroductionLessThanOrEqualTo(String value) {
			addCriterion("Introduction <=", value, "introduction");
			return (Criteria) this;
		}

		public Criteria andIntroductionLike(String value) {
			addCriterion("Introduction like", value, "introduction");
			return (Criteria) this;
		}

		public Criteria andIntroductionNotLike(String value) {
			addCriterion("Introduction not like", value, "introduction");
			return (Criteria) this;
		}

		public Criteria andIntroductionIn(List<String> values) {
			addCriterion("Introduction in", values, "introduction");
			return (Criteria) this;
		}

		public Criteria andIntroductionNotIn(List<String> values) {
			addCriterion("Introduction not in", values, "introduction");
			return (Criteria) this;
		}

		public Criteria andIntroductionBetween(String value1, String value2) {
			addCriterion("Introduction between", value1, value2, "introduction");
			return (Criteria) this;
		}

		public Criteria andIntroductionNotBetween(String value1, String value2) {
			addCriterion("Introduction not between", value1, value2,
					"introduction");
			return (Criteria) this;
		}

		public Criteria andNamerequiredIsNull() {
			addCriterion("NameRequired is null");
			return (Criteria) this;
		}

		public Criteria andNamerequiredIsNotNull() {
			addCriterion("NameRequired is not null");
			return (Criteria) this;
		}

		public Criteria andNamerequiredEqualTo(Boolean value) {
			addCriterion("NameRequired =", value, "namerequired");
			return (Criteria) this;
		}

		public Criteria andNamerequiredNotEqualTo(Boolean value) {
			addCriterion("NameRequired <>", value, "namerequired");
			return (Criteria) this;
		}

		public Criteria andNamerequiredGreaterThan(Boolean value) {
			addCriterion("NameRequired >", value, "namerequired");
			return (Criteria) this;
		}

		public Criteria andNamerequiredGreaterThanOrEqualTo(Boolean value) {
			addCriterion("NameRequired >=", value, "namerequired");
			return (Criteria) this;
		}

		public Criteria andNamerequiredLessThan(Boolean value) {
			addCriterion("NameRequired <", value, "namerequired");
			return (Criteria) this;
		}

		public Criteria andNamerequiredLessThanOrEqualTo(Boolean value) {
			addCriterion("NameRequired <=", value, "namerequired");
			return (Criteria) this;
		}

		public Criteria andNamerequiredIn(List<Boolean> values) {
			addCriterion("NameRequired in", values, "namerequired");
			return (Criteria) this;
		}

		public Criteria andNamerequiredNotIn(List<Boolean> values) {
			addCriterion("NameRequired not in", values, "namerequired");
			return (Criteria) this;
		}

		public Criteria andNamerequiredBetween(Boolean value1, Boolean value2) {
			addCriterion("NameRequired between", value1, value2, "namerequired");
			return (Criteria) this;
		}

		public Criteria andNamerequiredNotBetween(Boolean value1, Boolean value2) {
			addCriterion("NameRequired not between", value1, value2,
					"namerequired");
			return (Criteria) this;
		}

		public Criteria andSexrequiredIsNull() {
			addCriterion("SexRequired is null");
			return (Criteria) this;
		}

		public Criteria andSexrequiredIsNotNull() {
			addCriterion("SexRequired is not null");
			return (Criteria) this;
		}

		public Criteria andSexrequiredEqualTo(Boolean value) {
			addCriterion("SexRequired =", value, "sexrequired");
			return (Criteria) this;
		}

		public Criteria andSexrequiredNotEqualTo(Boolean value) {
			addCriterion("SexRequired <>", value, "sexrequired");
			return (Criteria) this;
		}

		public Criteria andSexrequiredGreaterThan(Boolean value) {
			addCriterion("SexRequired >", value, "sexrequired");
			return (Criteria) this;
		}

		public Criteria andSexrequiredGreaterThanOrEqualTo(Boolean value) {
			addCriterion("SexRequired >=", value, "sexrequired");
			return (Criteria) this;
		}

		public Criteria andSexrequiredLessThan(Boolean value) {
			addCriterion("SexRequired <", value, "sexrequired");
			return (Criteria) this;
		}

		public Criteria andSexrequiredLessThanOrEqualTo(Boolean value) {
			addCriterion("SexRequired <=", value, "sexrequired");
			return (Criteria) this;
		}

		public Criteria andSexrequiredIn(List<Boolean> values) {
			addCriterion("SexRequired in", values, "sexrequired");
			return (Criteria) this;
		}

		public Criteria andSexrequiredNotIn(List<Boolean> values) {
			addCriterion("SexRequired not in", values, "sexrequired");
			return (Criteria) this;
		}

		public Criteria andSexrequiredBetween(Boolean value1, Boolean value2) {
			addCriterion("SexRequired between", value1, value2, "sexrequired");
			return (Criteria) this;
		}

		public Criteria andSexrequiredNotBetween(Boolean value1, Boolean value2) {
			addCriterion("SexRequired not between", value1, value2,
					"sexrequired");
			return (Criteria) this;
		}

		public Criteria andPhonerequiredIsNull() {
			addCriterion("PhoneRequired is null");
			return (Criteria) this;
		}

		public Criteria andPhonerequiredIsNotNull() {
			addCriterion("PhoneRequired is not null");
			return (Criteria) this;
		}

		public Criteria andPhonerequiredEqualTo(Boolean value) {
			addCriterion("PhoneRequired =", value, "phonerequired");
			return (Criteria) this;
		}

		public Criteria andPhonerequiredNotEqualTo(Boolean value) {
			addCriterion("PhoneRequired <>", value, "phonerequired");
			return (Criteria) this;
		}

		public Criteria andPhonerequiredGreaterThan(Boolean value) {
			addCriterion("PhoneRequired >", value, "phonerequired");
			return (Criteria) this;
		}

		public Criteria andPhonerequiredGreaterThanOrEqualTo(Boolean value) {
			addCriterion("PhoneRequired >=", value, "phonerequired");
			return (Criteria) this;
		}

		public Criteria andPhonerequiredLessThan(Boolean value) {
			addCriterion("PhoneRequired <", value, "phonerequired");
			return (Criteria) this;
		}

		public Criteria andPhonerequiredLessThanOrEqualTo(Boolean value) {
			addCriterion("PhoneRequired <=", value, "phonerequired");
			return (Criteria) this;
		}

		public Criteria andPhonerequiredIn(List<Boolean> values) {
			addCriterion("PhoneRequired in", values, "phonerequired");
			return (Criteria) this;
		}

		public Criteria andPhonerequiredNotIn(List<Boolean> values) {
			addCriterion("PhoneRequired not in", values, "phonerequired");
			return (Criteria) this;
		}

		public Criteria andPhonerequiredBetween(Boolean value1, Boolean value2) {
			addCriterion("PhoneRequired between", value1, value2,
					"phonerequired");
			return (Criteria) this;
		}

		public Criteria andPhonerequiredNotBetween(Boolean value1,
				Boolean value2) {
			addCriterion("PhoneRequired not between", value1, value2,
					"phonerequired");
			return (Criteria) this;
		}

		public Criteria andAddressrequiredIsNull() {
			addCriterion("AddressRequired is null");
			return (Criteria) this;
		}

		public Criteria andAddressrequiredIsNotNull() {
			addCriterion("AddressRequired is not null");
			return (Criteria) this;
		}

		public Criteria andAddressrequiredEqualTo(Boolean value) {
			addCriterion("AddressRequired =", value, "addressrequired");
			return (Criteria) this;
		}

		public Criteria andAddressrequiredNotEqualTo(Boolean value) {
			addCriterion("AddressRequired <>", value, "addressrequired");
			return (Criteria) this;
		}

		public Criteria andAddressrequiredGreaterThan(Boolean value) {
			addCriterion("AddressRequired >", value, "addressrequired");
			return (Criteria) this;
		}

		public Criteria andAddressrequiredGreaterThanOrEqualTo(Boolean value) {
			addCriterion("AddressRequired >=", value, "addressrequired");
			return (Criteria) this;
		}

		public Criteria andAddressrequiredLessThan(Boolean value) {
			addCriterion("AddressRequired <", value, "addressrequired");
			return (Criteria) this;
		}

		public Criteria andAddressrequiredLessThanOrEqualTo(Boolean value) {
			addCriterion("AddressRequired <=", value, "addressrequired");
			return (Criteria) this;
		}

		public Criteria andAddressrequiredIn(List<Boolean> values) {
			addCriterion("AddressRequired in", values, "addressrequired");
			return (Criteria) this;
		}

		public Criteria andAddressrequiredNotIn(List<Boolean> values) {
			addCriterion("AddressRequired not in", values, "addressrequired");
			return (Criteria) this;
		}

		public Criteria andAddressrequiredBetween(Boolean value1, Boolean value2) {
			addCriterion("AddressRequired between", value1, value2,
					"addressrequired");
			return (Criteria) this;
		}

		public Criteria andAddressrequiredNotBetween(Boolean value1,
				Boolean value2) {
			addCriterion("AddressRequired not between", value1, value2,
					"addressrequired");
			return (Criteria) this;
		}

		public Criteria andEmailrequiredIsNull() {
			addCriterion("EmailRequired is null");
			return (Criteria) this;
		}

		public Criteria andEmailrequiredIsNotNull() {
			addCriterion("EmailRequired is not null");
			return (Criteria) this;
		}

		public Criteria andEmailrequiredEqualTo(Boolean value) {
			addCriterion("EmailRequired =", value, "emailrequired");
			return (Criteria) this;
		}

		public Criteria andEmailrequiredNotEqualTo(Boolean value) {
			addCriterion("EmailRequired <>", value, "emailrequired");
			return (Criteria) this;
		}

		public Criteria andEmailrequiredGreaterThan(Boolean value) {
			addCriterion("EmailRequired >", value, "emailrequired");
			return (Criteria) this;
		}

		public Criteria andEmailrequiredGreaterThanOrEqualTo(Boolean value) {
			addCriterion("EmailRequired >=", value, "emailrequired");
			return (Criteria) this;
		}

		public Criteria andEmailrequiredLessThan(Boolean value) {
			addCriterion("EmailRequired <", value, "emailrequired");
			return (Criteria) this;
		}

		public Criteria andEmailrequiredLessThanOrEqualTo(Boolean value) {
			addCriterion("EmailRequired <=", value, "emailrequired");
			return (Criteria) this;
		}

		public Criteria andEmailrequiredIn(List<Boolean> values) {
			addCriterion("EmailRequired in", values, "emailrequired");
			return (Criteria) this;
		}

		public Criteria andEmailrequiredNotIn(List<Boolean> values) {
			addCriterion("EmailRequired not in", values, "emailrequired");
			return (Criteria) this;
		}

		public Criteria andEmailrequiredBetween(Boolean value1, Boolean value2) {
			addCriterion("EmailRequired between", value1, value2,
					"emailrequired");
			return (Criteria) this;
		}

		public Criteria andEmailrequiredNotBetween(Boolean value1,
				Boolean value2) {
			addCriterion("EmailRequired not between", value1, value2,
					"emailrequired");
			return (Criteria) this;
		}

		public Criteria andBirthdayrequiredIsNull() {
			addCriterion("BirthdayRequired is null");
			return (Criteria) this;
		}

		public Criteria andBirthdayrequiredIsNotNull() {
			addCriterion("BirthdayRequired is not null");
			return (Criteria) this;
		}

		public Criteria andBirthdayrequiredEqualTo(Boolean value) {
			addCriterion("BirthdayRequired =", value, "birthdayrequired");
			return (Criteria) this;
		}

		public Criteria andBirthdayrequiredNotEqualTo(Boolean value) {
			addCriterion("BirthdayRequired <>", value, "birthdayrequired");
			return (Criteria) this;
		}

		public Criteria andBirthdayrequiredGreaterThan(Boolean value) {
			addCriterion("BirthdayRequired >", value, "birthdayrequired");
			return (Criteria) this;
		}

		public Criteria andBirthdayrequiredGreaterThanOrEqualTo(Boolean value) {
			addCriterion("BirthdayRequired >=", value, "birthdayrequired");
			return (Criteria) this;
		}

		public Criteria andBirthdayrequiredLessThan(Boolean value) {
			addCriterion("BirthdayRequired <", value, "birthdayrequired");
			return (Criteria) this;
		}

		public Criteria andBirthdayrequiredLessThanOrEqualTo(Boolean value) {
			addCriterion("BirthdayRequired <=", value, "birthdayrequired");
			return (Criteria) this;
		}

		public Criteria andBirthdayrequiredIn(List<Boolean> values) {
			addCriterion("BirthdayRequired in", values, "birthdayrequired");
			return (Criteria) this;
		}

		public Criteria andBirthdayrequiredNotIn(List<Boolean> values) {
			addCriterion("BirthdayRequired not in", values, "birthdayrequired");
			return (Criteria) this;
		}

		public Criteria andBirthdayrequiredBetween(Boolean value1,
				Boolean value2) {
			addCriterion("BirthdayRequired between", value1, value2,
					"birthdayrequired");
			return (Criteria) this;
		}

		public Criteria andBirthdayrequiredNotBetween(Boolean value1,
				Boolean value2) {
			addCriterion("BirthdayRequired not between", value1, value2,
					"birthdayrequired");
			return (Criteria) this;
		}

		public Criteria andMembersettingIsNull() {
			addCriterion("MemberSetting is null");
			return (Criteria) this;
		}

		public Criteria andMembersettingIsNotNull() {
			addCriterion("MemberSetting is not null");
			return (Criteria) this;
		}

		public Criteria andMembersettingEqualTo(Boolean value) {
			addCriterion("MemberSetting =", value, "membersetting");
			return (Criteria) this;
		}

		public Criteria andMembersettingNotEqualTo(Boolean value) {
			addCriterion("MemberSetting <>", value, "membersetting");
			return (Criteria) this;
		}

		public Criteria andMembersettingGreaterThan(Boolean value) {
			addCriterion("MemberSetting >", value, "membersetting");
			return (Criteria) this;
		}

		public Criteria andMembersettingGreaterThanOrEqualTo(Boolean value) {
			addCriterion("MemberSetting >=", value, "membersetting");
			return (Criteria) this;
		}

		public Criteria andMembersettingLessThan(Boolean value) {
			addCriterion("MemberSetting <", value, "membersetting");
			return (Criteria) this;
		}

		public Criteria andMembersettingLessThanOrEqualTo(Boolean value) {
			addCriterion("MemberSetting <=", value, "membersetting");
			return (Criteria) this;
		}

		public Criteria andMembersettingIn(List<Boolean> values) {
			addCriterion("MemberSetting in", values, "membersetting");
			return (Criteria) this;
		}

		public Criteria andMembersettingNotIn(List<Boolean> values) {
			addCriterion("MemberSetting not in", values, "membersetting");
			return (Criteria) this;
		}

		public Criteria andMembersettingBetween(Boolean value1, Boolean value2) {
			addCriterion("MemberSetting between", value1, value2,
					"membersetting");
			return (Criteria) this;
		}

		public Criteria andMembersettingNotBetween(Boolean value1,
				Boolean value2) {
			addCriterion("MemberSetting not between", value1, value2,
					"membersetting");
			return (Criteria) this;
		}

		public Criteria andAmountrequiredIsNull() {
			addCriterion("AmountRequired is null");
			return (Criteria) this;
		}

		public Criteria andAmountrequiredIsNotNull() {
			addCriterion("AmountRequired is not null");
			return (Criteria) this;
		}

		public Criteria andAmountrequiredEqualTo(Integer value) {
			addCriterion("AmountRequired =", value, "amountrequired");
			return (Criteria) this;
		}

		public Criteria andAmountrequiredNotEqualTo(Integer value) {
			addCriterion("AmountRequired <>", value, "amountrequired");
			return (Criteria) this;
		}

		public Criteria andAmountrequiredGreaterThan(Integer value) {
			addCriterion("AmountRequired >", value, "amountrequired");
			return (Criteria) this;
		}

		public Criteria andAmountrequiredGreaterThanOrEqualTo(Integer value) {
			addCriterion("AmountRequired >=", value, "amountrequired");
			return (Criteria) this;
		}

		public Criteria andAmountrequiredLessThan(Integer value) {
			addCriterion("AmountRequired <", value, "amountrequired");
			return (Criteria) this;
		}

		public Criteria andAmountrequiredLessThanOrEqualTo(Integer value) {
			addCriterion("AmountRequired <=", value, "amountrequired");
			return (Criteria) this;
		}

		public Criteria andAmountrequiredIn(List<Integer> values) {
			addCriterion("AmountRequired in", values, "amountrequired");
			return (Criteria) this;
		}

		public Criteria andAmountrequiredNotIn(List<Integer> values) {
			addCriterion("AmountRequired not in", values, "amountrequired");
			return (Criteria) this;
		}

		public Criteria andAmountrequiredBetween(Integer value1, Integer value2) {
			addCriterion("AmountRequired between", value1, value2,
					"amountrequired");
			return (Criteria) this;
		}

		public Criteria andAmountrequiredNotBetween(Integer value1,
				Integer value2) {
			addCriterion("AmountRequired not between", value1, value2,
					"amountrequired");
			return (Criteria) this;
		}

		public Criteria andAmountcountrequiredIsNull() {
			addCriterion("AmountCountRequired is null");
			return (Criteria) this;
		}

		public Criteria andAmountcountrequiredIsNotNull() {
			addCriterion("AmountCountRequired is not null");
			return (Criteria) this;
		}

		public Criteria andAmountcountrequiredEqualTo(String value) {
			addCriterion("AmountCountRequired =", value, "amountcountrequired");
			return (Criteria) this;
		}

		public Criteria andAmountcountrequiredNotEqualTo(String value) {
			addCriterion("AmountCountRequired <>", value, "amountcountrequired");
			return (Criteria) this;
		}

		public Criteria andAmountcountrequiredGreaterThan(String value) {
			addCriterion("AmountCountRequired >", value, "amountcountrequired");
			return (Criteria) this;
		}

		public Criteria andAmountcountrequiredGreaterThanOrEqualTo(String value) {
			addCriterion("AmountCountRequired >=", value, "amountcountrequired");
			return (Criteria) this;
		}

		public Criteria andAmountcountrequiredLessThan(String value) {
			addCriterion("AmountCountRequired <", value, "amountcountrequired");
			return (Criteria) this;
		}

		public Criteria andAmountcountrequiredLessThanOrEqualTo(String value) {
			addCriterion("AmountCountRequired <=", value, "amountcountrequired");
			return (Criteria) this;
		}

		public Criteria andAmountcountrequiredLike(String value) {
			addCriterion("AmountCountRequired like", value,
					"amountcountrequired");
			return (Criteria) this;
		}

		public Criteria andAmountcountrequiredNotLike(String value) {
			addCriterion("AmountCountRequired not like", value,
					"amountcountrequired");
			return (Criteria) this;
		}

		public Criteria andAmountcountrequiredIn(List<String> values) {
			addCriterion("AmountCountRequired in", values,
					"amountcountrequired");
			return (Criteria) this;
		}

		public Criteria andAmountcountrequiredNotIn(List<String> values) {
			addCriterion("AmountCountRequired not in", values,
					"amountcountrequired");
			return (Criteria) this;
		}

		public Criteria andAmountcountrequiredBetween(String value1,
				String value2) {
			addCriterion("AmountCountRequired between", value1, value2,
					"amountcountrequired");
			return (Criteria) this;
		}

		public Criteria andAmountcountrequiredNotBetween(String value1,
				String value2) {
			addCriterion("AmountCountRequired not between", value1, value2,
					"amountcountrequired");
			return (Criteria) this;
		}

		public Criteria andScoreplayIsNull() {
			addCriterion("ScorePlay is null");
			return (Criteria) this;
		}

		public Criteria andScoreplayIsNotNull() {
			addCriterion("ScorePlay is not null");
			return (Criteria) this;
		}

		public Criteria andScoreplayEqualTo(Boolean value) {
			addCriterion("ScorePlay =", value, "scoreplay");
			return (Criteria) this;
		}

		public Criteria andScoreplayNotEqualTo(Boolean value) {
			addCriterion("ScorePlay <>", value, "scoreplay");
			return (Criteria) this;
		}

		public Criteria andScoreplayGreaterThan(Boolean value) {
			addCriterion("ScorePlay >", value, "scoreplay");
			return (Criteria) this;
		}

		public Criteria andScoreplayGreaterThanOrEqualTo(Boolean value) {
			addCriterion("ScorePlay >=", value, "scoreplay");
			return (Criteria) this;
		}

		public Criteria andScoreplayLessThan(Boolean value) {
			addCriterion("ScorePlay <", value, "scoreplay");
			return (Criteria) this;
		}

		public Criteria andScoreplayLessThanOrEqualTo(Boolean value) {
			addCriterion("ScorePlay <=", value, "scoreplay");
			return (Criteria) this;
		}

		public Criteria andScoreplayIn(List<Boolean> values) {
			addCriterion("ScorePlay in", values, "scoreplay");
			return (Criteria) this;
		}

		public Criteria andScoreplayNotIn(List<Boolean> values) {
			addCriterion("ScorePlay not in", values, "scoreplay");
			return (Criteria) this;
		}

		public Criteria andScoreplayBetween(Boolean value1, Boolean value2) {
			addCriterion("ScorePlay between", value1, value2, "scoreplay");
			return (Criteria) this;
		}

		public Criteria andScoreplayNotBetween(Boolean value1, Boolean value2) {
			addCriterion("ScorePlay not between", value1, value2, "scoreplay");
			return (Criteria) this;
		}

		public Criteria andCreateddateIsNull() {
			addCriterion("CreatedDate is null");
			return (Criteria) this;
		}

		public Criteria andCreateddateIsNotNull() {
			addCriterion("CreatedDate is not null");
			return (Criteria) this;
		}

		public Criteria andCreateddateEqualTo(Date value) {
			addCriterion("CreatedDate =", value, "createddate");
			return (Criteria) this;
		}

		public Criteria andCreateddateNotEqualTo(Date value) {
			addCriterion("CreatedDate <>", value, "createddate");
			return (Criteria) this;
		}

		public Criteria andCreateddateGreaterThan(Date value) {
			addCriterion("CreatedDate >", value, "createddate");
			return (Criteria) this;
		}

		public Criteria andCreateddateGreaterThanOrEqualTo(Date value) {
			addCriterion("CreatedDate >=", value, "createddate");
			return (Criteria) this;
		}

		public Criteria andCreateddateLessThan(Date value) {
			addCriterion("CreatedDate <", value, "createddate");
			return (Criteria) this;
		}

		public Criteria andCreateddateLessThanOrEqualTo(Date value) {
			addCriterion("CreatedDate <=", value, "createddate");
			return (Criteria) this;
		}

		public Criteria andCreateddateIn(List<Date> values) {
			addCriterion("CreatedDate in", values, "createddate");
			return (Criteria) this;
		}

		public Criteria andCreateddateNotIn(List<Date> values) {
			addCriterion("CreatedDate not in", values, "createddate");
			return (Criteria) this;
		}

		public Criteria andCreateddateBetween(Date value1, Date value2) {
			addCriterion("CreatedDate between", value1, value2, "createddate");
			return (Criteria) this;
		}

		public Criteria andCreateddateNotBetween(Date value1, Date value2) {
			addCriterion("CreatedDate not between", value1, value2,
					"createddate");
			return (Criteria) this;
		}

		public Criteria andModifieddateIsNull() {
			addCriterion("ModifiedDate is null");
			return (Criteria) this;
		}

		public Criteria andModifieddateIsNotNull() {
			addCriterion("ModifiedDate is not null");
			return (Criteria) this;
		}

		public Criteria andModifieddateEqualTo(Date value) {
			addCriterion("ModifiedDate =", value, "modifieddate");
			return (Criteria) this;
		}

		public Criteria andModifieddateNotEqualTo(Date value) {
			addCriterion("ModifiedDate <>", value, "modifieddate");
			return (Criteria) this;
		}

		public Criteria andModifieddateGreaterThan(Date value) {
			addCriterion("ModifiedDate >", value, "modifieddate");
			return (Criteria) this;
		}

		public Criteria andModifieddateGreaterThanOrEqualTo(Date value) {
			addCriterion("ModifiedDate >=", value, "modifieddate");
			return (Criteria) this;
		}

		public Criteria andModifieddateLessThan(Date value) {
			addCriterion("ModifiedDate <", value, "modifieddate");
			return (Criteria) this;
		}

		public Criteria andModifieddateLessThanOrEqualTo(Date value) {
			addCriterion("ModifiedDate <=", value, "modifieddate");
			return (Criteria) this;
		}

		public Criteria andModifieddateIn(List<Date> values) {
			addCriterion("ModifiedDate in", values, "modifieddate");
			return (Criteria) this;
		}

		public Criteria andModifieddateNotIn(List<Date> values) {
			addCriterion("ModifiedDate not in", values, "modifieddate");
			return (Criteria) this;
		}

		public Criteria andModifieddateBetween(Date value1, Date value2) {
			addCriterion("ModifiedDate between", value1, value2, "modifieddate");
			return (Criteria) this;
		}

		public Criteria andModifieddateNotBetween(Date value1, Date value2) {
			addCriterion("ModifiedDate not between", value1, value2,
					"modifieddate");
			return (Criteria) this;
		}

		public Criteria andUseridfkIsNull() {
			addCriterion("UserIDFK is null");
			return (Criteria) this;
		}

		public Criteria andUseridfkIsNotNull() {
			addCriterion("UserIDFK is not null");
			return (Criteria) this;
		}

		public Criteria andUseridfkEqualTo(Long value) {
			addCriterion("UserIDFK =", value, "useridfk");
			return (Criteria) this;
		}

		public Criteria andUseridfkNotEqualTo(Long value) {
			addCriterion("UserIDFK <>", value, "useridfk");
			return (Criteria) this;
		}

		public Criteria andUseridfkGreaterThan(Long value) {
			addCriterion("UserIDFK >", value, "useridfk");
			return (Criteria) this;
		}

		public Criteria andUseridfkGreaterThanOrEqualTo(Long value) {
			addCriterion("UserIDFK >=", value, "useridfk");
			return (Criteria) this;
		}

		public Criteria andUseridfkLessThan(Long value) {
			addCriterion("UserIDFK <", value, "useridfk");
			return (Criteria) this;
		}

		public Criteria andUseridfkLessThanOrEqualTo(Long value) {
			addCriterion("UserIDFK <=", value, "useridfk");
			return (Criteria) this;
		}

		public Criteria andUseridfkIn(List<Long> values) {
			addCriterion("UserIDFK in", values, "useridfk");
			return (Criteria) this;
		}

		public Criteria andUseridfkNotIn(List<Long> values) {
			addCriterion("UserIDFK not in", values, "useridfk");
			return (Criteria) this;
		}

		public Criteria andUseridfkBetween(Long value1, Long value2) {
			addCriterion("UserIDFK between", value1, value2, "useridfk");
			return (Criteria) this;
		}

		public Criteria andUseridfkNotBetween(Long value1, Long value2) {
			addCriterion("UserIDFK not between", value1, value2, "useridfk");
			return (Criteria) this;
		}

		public Criteria andBackgroundurlIsNull() {
			addCriterion("BackgroundUrl is null");
			return (Criteria) this;
		}

		public Criteria andBackgroundurlIsNotNull() {
			addCriterion("BackgroundUrl is not null");
			return (Criteria) this;
		}

		public Criteria andBackgroundurlEqualTo(String value) {
			addCriterion("BackgroundUrl =", value, "backgroundurl");
			return (Criteria) this;
		}

		public Criteria andBackgroundurlNotEqualTo(String value) {
			addCriterion("BackgroundUrl <>", value, "backgroundurl");
			return (Criteria) this;
		}

		public Criteria andBackgroundurlGreaterThan(String value) {
			addCriterion("BackgroundUrl >", value, "backgroundurl");
			return (Criteria) this;
		}

		public Criteria andBackgroundurlGreaterThanOrEqualTo(String value) {
			addCriterion("BackgroundUrl >=", value, "backgroundurl");
			return (Criteria) this;
		}

		public Criteria andBackgroundurlLessThan(String value) {
			addCriterion("BackgroundUrl <", value, "backgroundurl");
			return (Criteria) this;
		}

		public Criteria andBackgroundurlLessThanOrEqualTo(String value) {
			addCriterion("BackgroundUrl <=", value, "backgroundurl");
			return (Criteria) this;
		}

		public Criteria andBackgroundurlLike(String value) {
			addCriterion("BackgroundUrl like", value, "backgroundurl");
			return (Criteria) this;
		}

		public Criteria andBackgroundurlNotLike(String value) {
			addCriterion("BackgroundUrl not like", value, "backgroundurl");
			return (Criteria) this;
		}

		public Criteria andBackgroundurlIn(List<String> values) {
			addCriterion("BackgroundUrl in", values, "backgroundurl");
			return (Criteria) this;
		}

		public Criteria andBackgroundurlNotIn(List<String> values) {
			addCriterion("BackgroundUrl not in", values, "backgroundurl");
			return (Criteria) this;
		}

		public Criteria andBackgroundurlBetween(String value1, String value2) {
			addCriterion("BackgroundUrl between", value1, value2,
					"backgroundurl");
			return (Criteria) this;
		}

		public Criteria andBackgroundurlNotBetween(String value1, String value2) {
			addCriterion("BackgroundUrl not between", value1, value2,
					"backgroundurl");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table tb_merchant
	 * @mbggenerated  Tue Dec 31 16:48:21 CST 2013
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_merchant
     *
     * @mbggenerated do_not_delete_during_merge Mon Dec 16 21:27:17 CST 2013
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}