package com.dandelion.memberapp.model.po;

import java.util.Date;

public class User {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_user.ID
	 * @mbggenerated  Mon Nov 25 11:34:32 CST 2013
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_user.Alias
	 * @mbggenerated  Mon Nov 25 11:34:32 CST 2013
	 */
	private String alias;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_user.Password
	 * @mbggenerated  Mon Nov 25 11:34:32 CST 2013
	 */
	private String password;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_user.UserState
	 * @mbggenerated  Mon Nov 25 11:34:32 CST 2013
	 */
	private Boolean userstate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_user.UserEmail
	 * @mbggenerated  Mon Nov 25 11:34:32 CST 2013
	 */
	private String useremail;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_user.LoginState
	 * @mbggenerated  Mon Nov 25 11:34:32 CST 2013
	 */
	private Boolean loginstate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_user.IPAddress
	 * @mbggenerated  Mon Nov 25 11:34:32 CST 2013
	 */
	private String ipaddress;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_user.CreatedDate
	 * @mbggenerated  Mon Nov 25 11:34:32 CST 2013
	 */
	private Date createddate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_user.ModifiedDate
	 * @mbggenerated  Mon Nov 25 11:34:32 CST 2013
	 */
	private Date modifieddate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_user.IsDeleted
	 * @mbggenerated  Mon Nov 25 11:34:32 CST 2013
	 */
	private Boolean isdeleted;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_user.Birthday
	 * @mbggenerated  Mon Nov 25 11:34:32 CST 2013
	 */
	private Date birthday;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_user.Gender
	 * @mbggenerated  Mon Nov 25 11:34:32 CST 2013
	 */
	private Boolean gender;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_user.UserSignature
	 * @mbggenerated  Mon Nov 25 11:34:32 CST 2013
	 */
	private String usersignature;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_user.AvatarIDFK
	 * @mbggenerated  Mon Nov 25 11:34:32 CST 2013
	 */
	private String avataridfk;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_user.FriendCount
	 * @mbggenerated  Mon Nov 25 11:34:32 CST 2013
	 */
	private Integer friendcount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_user.FanCount
	 * @mbggenerated  Mon Nov 25 11:34:32 CST 2013
	 */
	private Integer fancount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_user.FollowCount
	 * @mbggenerated  Mon Nov 25 11:34:32 CST 2013
	 */
	private Integer followcount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_user.ArticleCount
	 * @mbggenerated  Mon Nov 25 11:34:32 CST 2013
	 */
	private Integer articlecount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_user.RegisterFrom
	 * @mbggenerated  Mon Nov 25 11:34:32 CST 2013
	 */
	private Integer registerfrom;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_user.BackgroundUrl
	 * @mbggenerated  Mon Nov 25 11:34:32 CST 2013
	 */
	private String backgroundurl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_user.PhoneNumber
	 * @mbggenerated  Mon Nov 25 11:34:32 CST 2013
	 */
	private String phonenumber;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tb_user.AccountType
	 * @mbggenerated  Mon Nov 25 11:34:32 CST 2013
	 */
	private Integer accounttype;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_user.ID
	 * @return  the value of tb_user.ID
	 * @mbggenerated  Mon Nov 25 11:34:32 CST 2013
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_user.ID
	 * @param id  the value for tb_user.ID
	 * @mbggenerated  Mon Nov 25 11:34:32 CST 2013
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_user.Alias
	 * @return  the value of tb_user.Alias
	 * @mbggenerated  Mon Nov 25 11:34:32 CST 2013
	 */
	public String getAlias() {
		return alias;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_user.Alias
	 * @param alias  the value for tb_user.Alias
	 * @mbggenerated  Mon Nov 25 11:34:32 CST 2013
	 */
	public void setAlias(String alias) {
		this.alias = alias;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_user.Password
	 * @return  the value of tb_user.Password
	 * @mbggenerated  Mon Nov 25 11:34:32 CST 2013
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_user.Password
	 * @param password  the value for tb_user.Password
	 * @mbggenerated  Mon Nov 25 11:34:32 CST 2013
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_user.UserState
	 * @return  the value of tb_user.UserState
	 * @mbggenerated  Mon Nov 25 11:34:32 CST 2013
	 */
	public Boolean getUserstate() {
		return userstate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_user.UserState
	 * @param userstate  the value for tb_user.UserState
	 * @mbggenerated  Mon Nov 25 11:34:32 CST 2013
	 */
	public void setUserstate(Boolean userstate) {
		this.userstate = userstate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_user.UserEmail
	 * @return  the value of tb_user.UserEmail
	 * @mbggenerated  Mon Nov 25 11:34:32 CST 2013
	 */
	public String getUseremail() {
		return useremail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_user.UserEmail
	 * @param useremail  the value for tb_user.UserEmail
	 * @mbggenerated  Mon Nov 25 11:34:32 CST 2013
	 */
	public void setUseremail(String useremail) {
		this.useremail = useremail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_user.LoginState
	 * @return  the value of tb_user.LoginState
	 * @mbggenerated  Mon Nov 25 11:34:32 CST 2013
	 */
	public Boolean getLoginstate() {
		return loginstate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_user.LoginState
	 * @param loginstate  the value for tb_user.LoginState
	 * @mbggenerated  Mon Nov 25 11:34:32 CST 2013
	 */
	public void setLoginstate(Boolean loginstate) {
		this.loginstate = loginstate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_user.IPAddress
	 * @return  the value of tb_user.IPAddress
	 * @mbggenerated  Mon Nov 25 11:34:32 CST 2013
	 */
	public String getIpaddress() {
		return ipaddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_user.IPAddress
	 * @param ipaddress  the value for tb_user.IPAddress
	 * @mbggenerated  Mon Nov 25 11:34:32 CST 2013
	 */
	public void setIpaddress(String ipaddress) {
		this.ipaddress = ipaddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_user.CreatedDate
	 * @return  the value of tb_user.CreatedDate
	 * @mbggenerated  Mon Nov 25 11:34:32 CST 2013
	 */
	public Date getCreateddate() {
		return createddate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_user.CreatedDate
	 * @param createddate  the value for tb_user.CreatedDate
	 * @mbggenerated  Mon Nov 25 11:34:32 CST 2013
	 */
	public void setCreateddate(Date createddate) {
		this.createddate = createddate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_user.ModifiedDate
	 * @return  the value of tb_user.ModifiedDate
	 * @mbggenerated  Mon Nov 25 11:34:32 CST 2013
	 */
	public Date getModifieddate() {
		return modifieddate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_user.ModifiedDate
	 * @param modifieddate  the value for tb_user.ModifiedDate
	 * @mbggenerated  Mon Nov 25 11:34:32 CST 2013
	 */
	public void setModifieddate(Date modifieddate) {
		this.modifieddate = modifieddate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_user.IsDeleted
	 * @return  the value of tb_user.IsDeleted
	 * @mbggenerated  Mon Nov 25 11:34:32 CST 2013
	 */
	public Boolean getIsdeleted() {
		return isdeleted;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_user.IsDeleted
	 * @param isdeleted  the value for tb_user.IsDeleted
	 * @mbggenerated  Mon Nov 25 11:34:32 CST 2013
	 */
	public void setIsdeleted(Boolean isdeleted) {
		this.isdeleted = isdeleted;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_user.Birthday
	 * @return  the value of tb_user.Birthday
	 * @mbggenerated  Mon Nov 25 11:34:32 CST 2013
	 */
	public Date getBirthday() {
		return birthday;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_user.Birthday
	 * @param birthday  the value for tb_user.Birthday
	 * @mbggenerated  Mon Nov 25 11:34:32 CST 2013
	 */
	public void setBirthday(Date birthday) {
		this.birthday = birthday;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_user.Gender
	 * @return  the value of tb_user.Gender
	 * @mbggenerated  Mon Nov 25 11:34:32 CST 2013
	 */
	public Boolean getGender() {
		return gender;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_user.Gender
	 * @param gender  the value for tb_user.Gender
	 * @mbggenerated  Mon Nov 25 11:34:32 CST 2013
	 */
	public void setGender(Boolean gender) {
		this.gender = gender;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_user.UserSignature
	 * @return  the value of tb_user.UserSignature
	 * @mbggenerated  Mon Nov 25 11:34:32 CST 2013
	 */
	public String getUsersignature() {
		return usersignature;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_user.UserSignature
	 * @param usersignature  the value for tb_user.UserSignature
	 * @mbggenerated  Mon Nov 25 11:34:32 CST 2013
	 */
	public void setUsersignature(String usersignature) {
		this.usersignature = usersignature;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_user.AvatarIDFK
	 * @return  the value of tb_user.AvatarIDFK
	 * @mbggenerated  Mon Nov 25 11:34:32 CST 2013
	 */
	public String getAvataridfk() {
		return avataridfk;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_user.AvatarIDFK
	 * @param avataridfk  the value for tb_user.AvatarIDFK
	 * @mbggenerated  Mon Nov 25 11:34:32 CST 2013
	 */
	public void setAvataridfk(String avataridfk) {
		this.avataridfk = avataridfk;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_user.FriendCount
	 * @return  the value of tb_user.FriendCount
	 * @mbggenerated  Mon Nov 25 11:34:32 CST 2013
	 */
	public Integer getFriendcount() {
		return friendcount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_user.FriendCount
	 * @param friendcount  the value for tb_user.FriendCount
	 * @mbggenerated  Mon Nov 25 11:34:32 CST 2013
	 */
	public void setFriendcount(Integer friendcount) {
		this.friendcount = friendcount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_user.FanCount
	 * @return  the value of tb_user.FanCount
	 * @mbggenerated  Mon Nov 25 11:34:32 CST 2013
	 */
	public Integer getFancount() {
		return fancount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_user.FanCount
	 * @param fancount  the value for tb_user.FanCount
	 * @mbggenerated  Mon Nov 25 11:34:32 CST 2013
	 */
	public void setFancount(Integer fancount) {
		this.fancount = fancount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_user.FollowCount
	 * @return  the value of tb_user.FollowCount
	 * @mbggenerated  Mon Nov 25 11:34:32 CST 2013
	 */
	public Integer getFollowcount() {
		return followcount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_user.FollowCount
	 * @param followcount  the value for tb_user.FollowCount
	 * @mbggenerated  Mon Nov 25 11:34:32 CST 2013
	 */
	public void setFollowcount(Integer followcount) {
		this.followcount = followcount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_user.ArticleCount
	 * @return  the value of tb_user.ArticleCount
	 * @mbggenerated  Mon Nov 25 11:34:32 CST 2013
	 */
	public Integer getArticlecount() {
		return articlecount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_user.ArticleCount
	 * @param articlecount  the value for tb_user.ArticleCount
	 * @mbggenerated  Mon Nov 25 11:34:32 CST 2013
	 */
	public void setArticlecount(Integer articlecount) {
		this.articlecount = articlecount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_user.RegisterFrom
	 * @return  the value of tb_user.RegisterFrom
	 * @mbggenerated  Mon Nov 25 11:34:32 CST 2013
	 */
	public Integer getRegisterfrom() {
		return registerfrom;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_user.RegisterFrom
	 * @param registerfrom  the value for tb_user.RegisterFrom
	 * @mbggenerated  Mon Nov 25 11:34:32 CST 2013
	 */
	public void setRegisterfrom(Integer registerfrom) {
		this.registerfrom = registerfrom;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_user.BackgroundUrl
	 * @return  the value of tb_user.BackgroundUrl
	 * @mbggenerated  Mon Nov 25 11:34:32 CST 2013
	 */
	public String getBackgroundurl() {
		return backgroundurl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_user.BackgroundUrl
	 * @param backgroundurl  the value for tb_user.BackgroundUrl
	 * @mbggenerated  Mon Nov 25 11:34:32 CST 2013
	 */
	public void setBackgroundurl(String backgroundurl) {
		this.backgroundurl = backgroundurl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_user.PhoneNumber
	 * @return  the value of tb_user.PhoneNumber
	 * @mbggenerated  Mon Nov 25 11:34:32 CST 2013
	 */
	public String getPhonenumber() {
		return phonenumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_user.PhoneNumber
	 * @param phonenumber  the value for tb_user.PhoneNumber
	 * @mbggenerated  Mon Nov 25 11:34:32 CST 2013
	 */
	public void setPhonenumber(String phonenumber) {
		this.phonenumber = phonenumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tb_user.AccountType
	 * @return  the value of tb_user.AccountType
	 * @mbggenerated  Mon Nov 25 11:34:32 CST 2013
	 */
	public Integer getAccounttype() {
		return accounttype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tb_user.AccountType
	 * @param accounttype  the value for tb_user.AccountType
	 * @mbggenerated  Mon Nov 25 11:34:32 CST 2013
	 */
	public void setAccounttype(Integer accounttype) {
		this.accounttype = accounttype;
	}
}