package com.dandelion.memberapp.model.po;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class WsusersessionExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table tb_wsusersession
	 * @mbggenerated  Mon Nov 25 11:34:32 CST 2013
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table tb_wsusersession
	 * @mbggenerated  Mon Nov 25 11:34:32 CST 2013
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table tb_wsusersession
	 * @mbggenerated  Mon Nov 25 11:34:32 CST 2013
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_wsusersession
	 * @mbggenerated  Mon Nov 25 11:34:32 CST 2013
	 */
	public WsusersessionExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_wsusersession
	 * @mbggenerated  Mon Nov 25 11:34:32 CST 2013
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_wsusersession
	 * @mbggenerated  Mon Nov 25 11:34:32 CST 2013
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_wsusersession
	 * @mbggenerated  Mon Nov 25 11:34:32 CST 2013
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_wsusersession
	 * @mbggenerated  Mon Nov 25 11:34:32 CST 2013
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_wsusersession
	 * @mbggenerated  Mon Nov 25 11:34:32 CST 2013
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_wsusersession
	 * @mbggenerated  Mon Nov 25 11:34:32 CST 2013
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_wsusersession
	 * @mbggenerated  Mon Nov 25 11:34:32 CST 2013
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_wsusersession
	 * @mbggenerated  Mon Nov 25 11:34:32 CST 2013
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_wsusersession
	 * @mbggenerated  Mon Nov 25 11:34:32 CST 2013
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_wsusersession
	 * @mbggenerated  Mon Nov 25 11:34:32 CST 2013
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table tb_wsusersession
	 * @mbggenerated  Mon Nov 25 11:34:32 CST 2013
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("ID is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("ID is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(String value) {
			addCriterion("ID =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(String value) {
			addCriterion("ID <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(String value) {
			addCriterion("ID >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(String value) {
			addCriterion("ID >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(String value) {
			addCriterion("ID <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(String value) {
			addCriterion("ID <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLike(String value) {
			addCriterion("ID like", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotLike(String value) {
			addCriterion("ID not like", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<String> values) {
			addCriterion("ID in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<String> values) {
			addCriterion("ID not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(String value1, String value2) {
			addCriterion("ID between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(String value1, String value2) {
			addCriterion("ID not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andSessionkeyIsNull() {
			addCriterion("SessionKey is null");
			return (Criteria) this;
		}

		public Criteria andSessionkeyIsNotNull() {
			addCriterion("SessionKey is not null");
			return (Criteria) this;
		}

		public Criteria andSessionkeyEqualTo(Integer value) {
			addCriterion("SessionKey =", value, "sessionkey");
			return (Criteria) this;
		}

		public Criteria andSessionkeyNotEqualTo(Integer value) {
			addCriterion("SessionKey <>", value, "sessionkey");
			return (Criteria) this;
		}

		public Criteria andSessionkeyGreaterThan(Integer value) {
			addCriterion("SessionKey >", value, "sessionkey");
			return (Criteria) this;
		}

		public Criteria andSessionkeyGreaterThanOrEqualTo(Integer value) {
			addCriterion("SessionKey >=", value, "sessionkey");
			return (Criteria) this;
		}

		public Criteria andSessionkeyLessThan(Integer value) {
			addCriterion("SessionKey <", value, "sessionkey");
			return (Criteria) this;
		}

		public Criteria andSessionkeyLessThanOrEqualTo(Integer value) {
			addCriterion("SessionKey <=", value, "sessionkey");
			return (Criteria) this;
		}

		public Criteria andSessionkeyIn(List<Integer> values) {
			addCriterion("SessionKey in", values, "sessionkey");
			return (Criteria) this;
		}

		public Criteria andSessionkeyNotIn(List<Integer> values) {
			addCriterion("SessionKey not in", values, "sessionkey");
			return (Criteria) this;
		}

		public Criteria andSessionkeyBetween(Integer value1, Integer value2) {
			addCriterion("SessionKey between", value1, value2, "sessionkey");
			return (Criteria) this;
		}

		public Criteria andSessionkeyNotBetween(Integer value1, Integer value2) {
			addCriterion("SessionKey not between", value1, value2, "sessionkey");
			return (Criteria) this;
		}

		public Criteria andUseridfkIsNull() {
			addCriterion("UserIDFK is null");
			return (Criteria) this;
		}

		public Criteria andUseridfkIsNotNull() {
			addCriterion("UserIDFK is not null");
			return (Criteria) this;
		}

		public Criteria andUseridfkEqualTo(Long value) {
			addCriterion("UserIDFK =", value, "useridfk");
			return (Criteria) this;
		}

		public Criteria andUseridfkNotEqualTo(Long value) {
			addCriterion("UserIDFK <>", value, "useridfk");
			return (Criteria) this;
		}

		public Criteria andUseridfkGreaterThan(Long value) {
			addCriterion("UserIDFK >", value, "useridfk");
			return (Criteria) this;
		}

		public Criteria andUseridfkGreaterThanOrEqualTo(Long value) {
			addCriterion("UserIDFK >=", value, "useridfk");
			return (Criteria) this;
		}

		public Criteria andUseridfkLessThan(Long value) {
			addCriterion("UserIDFK <", value, "useridfk");
			return (Criteria) this;
		}

		public Criteria andUseridfkLessThanOrEqualTo(Long value) {
			addCriterion("UserIDFK <=", value, "useridfk");
			return (Criteria) this;
		}

		public Criteria andUseridfkIn(List<Long> values) {
			addCriterion("UserIDFK in", values, "useridfk");
			return (Criteria) this;
		}

		public Criteria andUseridfkNotIn(List<Long> values) {
			addCriterion("UserIDFK not in", values, "useridfk");
			return (Criteria) this;
		}

		public Criteria andUseridfkBetween(Long value1, Long value2) {
			addCriterion("UserIDFK between", value1, value2, "useridfk");
			return (Criteria) this;
		}

		public Criteria andUseridfkNotBetween(Long value1, Long value2) {
			addCriterion("UserIDFK not between", value1, value2, "useridfk");
			return (Criteria) this;
		}

		public Criteria andDeviceidentifierIsNull() {
			addCriterion("DeviceIdentifier is null");
			return (Criteria) this;
		}

		public Criteria andDeviceidentifierIsNotNull() {
			addCriterion("DeviceIdentifier is not null");
			return (Criteria) this;
		}

		public Criteria andDeviceidentifierEqualTo(String value) {
			addCriterion("DeviceIdentifier =", value, "deviceidentifier");
			return (Criteria) this;
		}

		public Criteria andDeviceidentifierNotEqualTo(String value) {
			addCriterion("DeviceIdentifier <>", value, "deviceidentifier");
			return (Criteria) this;
		}

		public Criteria andDeviceidentifierGreaterThan(String value) {
			addCriterion("DeviceIdentifier >", value, "deviceidentifier");
			return (Criteria) this;
		}

		public Criteria andDeviceidentifierGreaterThanOrEqualTo(String value) {
			addCriterion("DeviceIdentifier >=", value, "deviceidentifier");
			return (Criteria) this;
		}

		public Criteria andDeviceidentifierLessThan(String value) {
			addCriterion("DeviceIdentifier <", value, "deviceidentifier");
			return (Criteria) this;
		}

		public Criteria andDeviceidentifierLessThanOrEqualTo(String value) {
			addCriterion("DeviceIdentifier <=", value, "deviceidentifier");
			return (Criteria) this;
		}

		public Criteria andDeviceidentifierLike(String value) {
			addCriterion("DeviceIdentifier like", value, "deviceidentifier");
			return (Criteria) this;
		}

		public Criteria andDeviceidentifierNotLike(String value) {
			addCriterion("DeviceIdentifier not like", value, "deviceidentifier");
			return (Criteria) this;
		}

		public Criteria andDeviceidentifierIn(List<String> values) {
			addCriterion("DeviceIdentifier in", values, "deviceidentifier");
			return (Criteria) this;
		}

		public Criteria andDeviceidentifierNotIn(List<String> values) {
			addCriterion("DeviceIdentifier not in", values, "deviceidentifier");
			return (Criteria) this;
		}

		public Criteria andDeviceidentifierBetween(String value1, String value2) {
			addCriterion("DeviceIdentifier between", value1, value2,
					"deviceidentifier");
			return (Criteria) this;
		}

		public Criteria andDeviceidentifierNotBetween(String value1,
				String value2) {
			addCriterion("DeviceIdentifier not between", value1, value2,
					"deviceidentifier");
			return (Criteria) this;
		}

		public Criteria andPackagenameIsNull() {
			addCriterion("PackageName is null");
			return (Criteria) this;
		}

		public Criteria andPackagenameIsNotNull() {
			addCriterion("PackageName is not null");
			return (Criteria) this;
		}

		public Criteria andPackagenameEqualTo(String value) {
			addCriterion("PackageName =", value, "packagename");
			return (Criteria) this;
		}

		public Criteria andPackagenameNotEqualTo(String value) {
			addCriterion("PackageName <>", value, "packagename");
			return (Criteria) this;
		}

		public Criteria andPackagenameGreaterThan(String value) {
			addCriterion("PackageName >", value, "packagename");
			return (Criteria) this;
		}

		public Criteria andPackagenameGreaterThanOrEqualTo(String value) {
			addCriterion("PackageName >=", value, "packagename");
			return (Criteria) this;
		}

		public Criteria andPackagenameLessThan(String value) {
			addCriterion("PackageName <", value, "packagename");
			return (Criteria) this;
		}

		public Criteria andPackagenameLessThanOrEqualTo(String value) {
			addCriterion("PackageName <=", value, "packagename");
			return (Criteria) this;
		}

		public Criteria andPackagenameLike(String value) {
			addCriterion("PackageName like", value, "packagename");
			return (Criteria) this;
		}

		public Criteria andPackagenameNotLike(String value) {
			addCriterion("PackageName not like", value, "packagename");
			return (Criteria) this;
		}

		public Criteria andPackagenameIn(List<String> values) {
			addCriterion("PackageName in", values, "packagename");
			return (Criteria) this;
		}

		public Criteria andPackagenameNotIn(List<String> values) {
			addCriterion("PackageName not in", values, "packagename");
			return (Criteria) this;
		}

		public Criteria andPackagenameBetween(String value1, String value2) {
			addCriterion("PackageName between", value1, value2, "packagename");
			return (Criteria) this;
		}

		public Criteria andPackagenameNotBetween(String value1, String value2) {
			addCriterion("PackageName not between", value1, value2,
					"packagename");
			return (Criteria) this;
		}

		public Criteria andCreateddateIsNull() {
			addCriterion("CreatedDate is null");
			return (Criteria) this;
		}

		public Criteria andCreateddateIsNotNull() {
			addCriterion("CreatedDate is not null");
			return (Criteria) this;
		}

		public Criteria andCreateddateEqualTo(Date value) {
			addCriterion("CreatedDate =", value, "createddate");
			return (Criteria) this;
		}

		public Criteria andCreateddateNotEqualTo(Date value) {
			addCriterion("CreatedDate <>", value, "createddate");
			return (Criteria) this;
		}

		public Criteria andCreateddateGreaterThan(Date value) {
			addCriterion("CreatedDate >", value, "createddate");
			return (Criteria) this;
		}

		public Criteria andCreateddateGreaterThanOrEqualTo(Date value) {
			addCriterion("CreatedDate >=", value, "createddate");
			return (Criteria) this;
		}

		public Criteria andCreateddateLessThan(Date value) {
			addCriterion("CreatedDate <", value, "createddate");
			return (Criteria) this;
		}

		public Criteria andCreateddateLessThanOrEqualTo(Date value) {
			addCriterion("CreatedDate <=", value, "createddate");
			return (Criteria) this;
		}

		public Criteria andCreateddateIn(List<Date> values) {
			addCriterion("CreatedDate in", values, "createddate");
			return (Criteria) this;
		}

		public Criteria andCreateddateNotIn(List<Date> values) {
			addCriterion("CreatedDate not in", values, "createddate");
			return (Criteria) this;
		}

		public Criteria andCreateddateBetween(Date value1, Date value2) {
			addCriterion("CreatedDate between", value1, value2, "createddate");
			return (Criteria) this;
		}

		public Criteria andCreateddateNotBetween(Date value1, Date value2) {
			addCriterion("CreatedDate not between", value1, value2,
					"createddate");
			return (Criteria) this;
		}

		public Criteria andAccounttypeIsNull() {
			addCriterion("AccountType is null");
			return (Criteria) this;
		}

		public Criteria andAccounttypeIsNotNull() {
			addCriterion("AccountType is not null");
			return (Criteria) this;
		}

		public Criteria andAccounttypeEqualTo(Integer value) {
			addCriterion("AccountType =", value, "accounttype");
			return (Criteria) this;
		}

		public Criteria andAccounttypeNotEqualTo(Integer value) {
			addCriterion("AccountType <>", value, "accounttype");
			return (Criteria) this;
		}

		public Criteria andAccounttypeGreaterThan(Integer value) {
			addCriterion("AccountType >", value, "accounttype");
			return (Criteria) this;
		}

		public Criteria andAccounttypeGreaterThanOrEqualTo(Integer value) {
			addCriterion("AccountType >=", value, "accounttype");
			return (Criteria) this;
		}

		public Criteria andAccounttypeLessThan(Integer value) {
			addCriterion("AccountType <", value, "accounttype");
			return (Criteria) this;
		}

		public Criteria andAccounttypeLessThanOrEqualTo(Integer value) {
			addCriterion("AccountType <=", value, "accounttype");
			return (Criteria) this;
		}

		public Criteria andAccounttypeIn(List<Integer> values) {
			addCriterion("AccountType in", values, "accounttype");
			return (Criteria) this;
		}

		public Criteria andAccounttypeNotIn(List<Integer> values) {
			addCriterion("AccountType not in", values, "accounttype");
			return (Criteria) this;
		}

		public Criteria andAccounttypeBetween(Integer value1, Integer value2) {
			addCriterion("AccountType between", value1, value2, "accounttype");
			return (Criteria) this;
		}

		public Criteria andAccounttypeNotBetween(Integer value1, Integer value2) {
			addCriterion("AccountType not between", value1, value2,
					"accounttype");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table tb_wsusersession
	 * @mbggenerated  Mon Nov 25 11:34:32 CST 2013
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_wsusersession
     *
     * @mbggenerated do_not_delete_during_merge Sun Oct 27 22:52:00 CST 2013
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}