package com.dandelion.memberapp.dao.model;

import java.util.Date;

public class Emailbean {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_emailbean.id
     *
     * @mbggenerated Thu Oct 31 10:13:08 CST 2013
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_emailbean.token
     *
     * @mbggenerated Thu Oct 31 10:13:08 CST 2013
     */
    private String token;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_emailbean.expire
     *
     * @mbggenerated Thu Oct 31 10:13:08 CST 2013
     */
    private Date expire;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_emailbean.id
     *
     * @return the value of tb_emailbean.id
     *
     * @mbggenerated Thu Oct 31 10:13:08 CST 2013
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_emailbean.id
     *
     * @param id the value for tb_emailbean.id
     *
     * @mbggenerated Thu Oct 31 10:13:08 CST 2013
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_emailbean.token
     *
     * @return the value of tb_emailbean.token
     *
     * @mbggenerated Thu Oct 31 10:13:08 CST 2013
     */
    public String getToken() {
        return token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_emailbean.token
     *
     * @param token the value for tb_emailbean.token
     *
     * @mbggenerated Thu Oct 31 10:13:08 CST 2013
     */
    public void setToken(String token) {
        this.token = token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_emailbean.expire
     *
     * @return the value of tb_emailbean.expire
     *
     * @mbggenerated Thu Oct 31 10:13:08 CST 2013
     */
    public Date getExpire() {
        return expire;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_emailbean.expire
     *
     * @param expire the value for tb_emailbean.expire
     *
     * @mbggenerated Thu Oct 31 10:13:08 CST 2013
     */
    public void setExpire(Date expire) {
        this.expire = expire;
    }
}