package com.dandelion.memberapp.dao.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class UserExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table tb_user
	 * @mbggenerated  Thu Oct 31 10:13:08 CST 2013
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table tb_user
	 * @mbggenerated  Thu Oct 31 10:13:08 CST 2013
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table tb_user
	 * @mbggenerated  Thu Oct 31 10:13:08 CST 2013
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_user
	 * @mbggenerated  Thu Oct 31 10:13:08 CST 2013
	 */
	public UserExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_user
	 * @mbggenerated  Thu Oct 31 10:13:08 CST 2013
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_user
	 * @mbggenerated  Thu Oct 31 10:13:08 CST 2013
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_user
	 * @mbggenerated  Thu Oct 31 10:13:08 CST 2013
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_user
	 * @mbggenerated  Thu Oct 31 10:13:08 CST 2013
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_user
	 * @mbggenerated  Thu Oct 31 10:13:08 CST 2013
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_user
	 * @mbggenerated  Thu Oct 31 10:13:08 CST 2013
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_user
	 * @mbggenerated  Thu Oct 31 10:13:08 CST 2013
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_user
	 * @mbggenerated  Thu Oct 31 10:13:08 CST 2013
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_user
	 * @mbggenerated  Thu Oct 31 10:13:08 CST 2013
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_user
	 * @mbggenerated  Thu Oct 31 10:13:08 CST 2013
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table tb_user
	 * @mbggenerated  Thu Oct 31 10:13:08 CST 2013
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("ID is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("ID is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(String value) {
			addCriterion("ID =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(String value) {
			addCriterion("ID <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(String value) {
			addCriterion("ID >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(String value) {
			addCriterion("ID >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(String value) {
			addCriterion("ID <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(String value) {
			addCriterion("ID <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLike(String value) {
			addCriterion("ID like", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotLike(String value) {
			addCriterion("ID not like", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<String> values) {
			addCriterion("ID in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<String> values) {
			addCriterion("ID not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(String value1, String value2) {
			addCriterion("ID between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(String value1, String value2) {
			addCriterion("ID not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andAliasIsNull() {
			addCriterion("Alias is null");
			return (Criteria) this;
		}

		public Criteria andAliasIsNotNull() {
			addCriterion("Alias is not null");
			return (Criteria) this;
		}

		public Criteria andAliasEqualTo(String value) {
			addCriterion("Alias =", value, "alias");
			return (Criteria) this;
		}

		public Criteria andAliasNotEqualTo(String value) {
			addCriterion("Alias <>", value, "alias");
			return (Criteria) this;
		}

		public Criteria andAliasGreaterThan(String value) {
			addCriterion("Alias >", value, "alias");
			return (Criteria) this;
		}

		public Criteria andAliasGreaterThanOrEqualTo(String value) {
			addCriterion("Alias >=", value, "alias");
			return (Criteria) this;
		}

		public Criteria andAliasLessThan(String value) {
			addCriterion("Alias <", value, "alias");
			return (Criteria) this;
		}

		public Criteria andAliasLessThanOrEqualTo(String value) {
			addCriterion("Alias <=", value, "alias");
			return (Criteria) this;
		}

		public Criteria andAliasLike(String value) {
			addCriterion("Alias like", value, "alias");
			return (Criteria) this;
		}

		public Criteria andAliasNotLike(String value) {
			addCriterion("Alias not like", value, "alias");
			return (Criteria) this;
		}

		public Criteria andAliasIn(List<String> values) {
			addCriterion("Alias in", values, "alias");
			return (Criteria) this;
		}

		public Criteria andAliasNotIn(List<String> values) {
			addCriterion("Alias not in", values, "alias");
			return (Criteria) this;
		}

		public Criteria andAliasBetween(String value1, String value2) {
			addCriterion("Alias between", value1, value2, "alias");
			return (Criteria) this;
		}

		public Criteria andAliasNotBetween(String value1, String value2) {
			addCriterion("Alias not between", value1, value2, "alias");
			return (Criteria) this;
		}

		public Criteria andPasswordIsNull() {
			addCriterion("Password is null");
			return (Criteria) this;
		}

		public Criteria andPasswordIsNotNull() {
			addCriterion("Password is not null");
			return (Criteria) this;
		}

		public Criteria andPasswordEqualTo(String value) {
			addCriterion("Password =", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordNotEqualTo(String value) {
			addCriterion("Password <>", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordGreaterThan(String value) {
			addCriterion("Password >", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordGreaterThanOrEqualTo(String value) {
			addCriterion("Password >=", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordLessThan(String value) {
			addCriterion("Password <", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordLessThanOrEqualTo(String value) {
			addCriterion("Password <=", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordLike(String value) {
			addCriterion("Password like", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordNotLike(String value) {
			addCriterion("Password not like", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordIn(List<String> values) {
			addCriterion("Password in", values, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordNotIn(List<String> values) {
			addCriterion("Password not in", values, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordBetween(String value1, String value2) {
			addCriterion("Password between", value1, value2, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordNotBetween(String value1, String value2) {
			addCriterion("Password not between", value1, value2, "password");
			return (Criteria) this;
		}

		public Criteria andUserstateIsNull() {
			addCriterion("UserState is null");
			return (Criteria) this;
		}

		public Criteria andUserstateIsNotNull() {
			addCriterion("UserState is not null");
			return (Criteria) this;
		}

		public Criteria andUserstateEqualTo(Boolean value) {
			addCriterion("UserState =", value, "userstate");
			return (Criteria) this;
		}

		public Criteria andUserstateNotEqualTo(Boolean value) {
			addCriterion("UserState <>", value, "userstate");
			return (Criteria) this;
		}

		public Criteria andUserstateGreaterThan(Boolean value) {
			addCriterion("UserState >", value, "userstate");
			return (Criteria) this;
		}

		public Criteria andUserstateGreaterThanOrEqualTo(Boolean value) {
			addCriterion("UserState >=", value, "userstate");
			return (Criteria) this;
		}

		public Criteria andUserstateLessThan(Boolean value) {
			addCriterion("UserState <", value, "userstate");
			return (Criteria) this;
		}

		public Criteria andUserstateLessThanOrEqualTo(Boolean value) {
			addCriterion("UserState <=", value, "userstate");
			return (Criteria) this;
		}

		public Criteria andUserstateIn(List<Boolean> values) {
			addCriterion("UserState in", values, "userstate");
			return (Criteria) this;
		}

		public Criteria andUserstateNotIn(List<Boolean> values) {
			addCriterion("UserState not in", values, "userstate");
			return (Criteria) this;
		}

		public Criteria andUserstateBetween(Boolean value1, Boolean value2) {
			addCriterion("UserState between", value1, value2, "userstate");
			return (Criteria) this;
		}

		public Criteria andUserstateNotBetween(Boolean value1, Boolean value2) {
			addCriterion("UserState not between", value1, value2, "userstate");
			return (Criteria) this;
		}

		public Criteria andUseremailIsNull() {
			addCriterion("UserEmail is null");
			return (Criteria) this;
		}

		public Criteria andUseremailIsNotNull() {
			addCriterion("UserEmail is not null");
			return (Criteria) this;
		}

		public Criteria andUseremailEqualTo(String value) {
			addCriterion("UserEmail =", value, "useremail");
			return (Criteria) this;
		}

		public Criteria andUseremailNotEqualTo(String value) {
			addCriterion("UserEmail <>", value, "useremail");
			return (Criteria) this;
		}

		public Criteria andUseremailGreaterThan(String value) {
			addCriterion("UserEmail >", value, "useremail");
			return (Criteria) this;
		}

		public Criteria andUseremailGreaterThanOrEqualTo(String value) {
			addCriterion("UserEmail >=", value, "useremail");
			return (Criteria) this;
		}

		public Criteria andUseremailLessThan(String value) {
			addCriterion("UserEmail <", value, "useremail");
			return (Criteria) this;
		}

		public Criteria andUseremailLessThanOrEqualTo(String value) {
			addCriterion("UserEmail <=", value, "useremail");
			return (Criteria) this;
		}

		public Criteria andUseremailLike(String value) {
			addCriterion("UserEmail like", value, "useremail");
			return (Criteria) this;
		}

		public Criteria andUseremailNotLike(String value) {
			addCriterion("UserEmail not like", value, "useremail");
			return (Criteria) this;
		}

		public Criteria andUseremailIn(List<String> values) {
			addCriterion("UserEmail in", values, "useremail");
			return (Criteria) this;
		}

		public Criteria andUseremailNotIn(List<String> values) {
			addCriterion("UserEmail not in", values, "useremail");
			return (Criteria) this;
		}

		public Criteria andUseremailBetween(String value1, String value2) {
			addCriterion("UserEmail between", value1, value2, "useremail");
			return (Criteria) this;
		}

		public Criteria andUseremailNotBetween(String value1, String value2) {
			addCriterion("UserEmail not between", value1, value2, "useremail");
			return (Criteria) this;
		}

		public Criteria andLoginstateIsNull() {
			addCriterion("LoginState is null");
			return (Criteria) this;
		}

		public Criteria andLoginstateIsNotNull() {
			addCriterion("LoginState is not null");
			return (Criteria) this;
		}

		public Criteria andLoginstateEqualTo(Boolean value) {
			addCriterion("LoginState =", value, "loginstate");
			return (Criteria) this;
		}

		public Criteria andLoginstateNotEqualTo(Boolean value) {
			addCriterion("LoginState <>", value, "loginstate");
			return (Criteria) this;
		}

		public Criteria andLoginstateGreaterThan(Boolean value) {
			addCriterion("LoginState >", value, "loginstate");
			return (Criteria) this;
		}

		public Criteria andLoginstateGreaterThanOrEqualTo(Boolean value) {
			addCriterion("LoginState >=", value, "loginstate");
			return (Criteria) this;
		}

		public Criteria andLoginstateLessThan(Boolean value) {
			addCriterion("LoginState <", value, "loginstate");
			return (Criteria) this;
		}

		public Criteria andLoginstateLessThanOrEqualTo(Boolean value) {
			addCriterion("LoginState <=", value, "loginstate");
			return (Criteria) this;
		}

		public Criteria andLoginstateIn(List<Boolean> values) {
			addCriterion("LoginState in", values, "loginstate");
			return (Criteria) this;
		}

		public Criteria andLoginstateNotIn(List<Boolean> values) {
			addCriterion("LoginState not in", values, "loginstate");
			return (Criteria) this;
		}

		public Criteria andLoginstateBetween(Boolean value1, Boolean value2) {
			addCriterion("LoginState between", value1, value2, "loginstate");
			return (Criteria) this;
		}

		public Criteria andLoginstateNotBetween(Boolean value1, Boolean value2) {
			addCriterion("LoginState not between", value1, value2, "loginstate");
			return (Criteria) this;
		}

		public Criteria andIpaddressIsNull() {
			addCriterion("IPAddress is null");
			return (Criteria) this;
		}

		public Criteria andIpaddressIsNotNull() {
			addCriterion("IPAddress is not null");
			return (Criteria) this;
		}

		public Criteria andIpaddressEqualTo(String value) {
			addCriterion("IPAddress =", value, "ipaddress");
			return (Criteria) this;
		}

		public Criteria andIpaddressNotEqualTo(String value) {
			addCriterion("IPAddress <>", value, "ipaddress");
			return (Criteria) this;
		}

		public Criteria andIpaddressGreaterThan(String value) {
			addCriterion("IPAddress >", value, "ipaddress");
			return (Criteria) this;
		}

		public Criteria andIpaddressGreaterThanOrEqualTo(String value) {
			addCriterion("IPAddress >=", value, "ipaddress");
			return (Criteria) this;
		}

		public Criteria andIpaddressLessThan(String value) {
			addCriterion("IPAddress <", value, "ipaddress");
			return (Criteria) this;
		}

		public Criteria andIpaddressLessThanOrEqualTo(String value) {
			addCriterion("IPAddress <=", value, "ipaddress");
			return (Criteria) this;
		}

		public Criteria andIpaddressLike(String value) {
			addCriterion("IPAddress like", value, "ipaddress");
			return (Criteria) this;
		}

		public Criteria andIpaddressNotLike(String value) {
			addCriterion("IPAddress not like", value, "ipaddress");
			return (Criteria) this;
		}

		public Criteria andIpaddressIn(List<String> values) {
			addCriterion("IPAddress in", values, "ipaddress");
			return (Criteria) this;
		}

		public Criteria andIpaddressNotIn(List<String> values) {
			addCriterion("IPAddress not in", values, "ipaddress");
			return (Criteria) this;
		}

		public Criteria andIpaddressBetween(String value1, String value2) {
			addCriterion("IPAddress between", value1, value2, "ipaddress");
			return (Criteria) this;
		}

		public Criteria andIpaddressNotBetween(String value1, String value2) {
			addCriterion("IPAddress not between", value1, value2, "ipaddress");
			return (Criteria) this;
		}

		public Criteria andCreateddateIsNull() {
			addCriterion("CreatedDate is null");
			return (Criteria) this;
		}

		public Criteria andCreateddateIsNotNull() {
			addCriterion("CreatedDate is not null");
			return (Criteria) this;
		}

		public Criteria andCreateddateEqualTo(Date value) {
			addCriterion("CreatedDate =", value, "createddate");
			return (Criteria) this;
		}

		public Criteria andCreateddateNotEqualTo(Date value) {
			addCriterion("CreatedDate <>", value, "createddate");
			return (Criteria) this;
		}

		public Criteria andCreateddateGreaterThan(Date value) {
			addCriterion("CreatedDate >", value, "createddate");
			return (Criteria) this;
		}

		public Criteria andCreateddateGreaterThanOrEqualTo(Date value) {
			addCriterion("CreatedDate >=", value, "createddate");
			return (Criteria) this;
		}

		public Criteria andCreateddateLessThan(Date value) {
			addCriterion("CreatedDate <", value, "createddate");
			return (Criteria) this;
		}

		public Criteria andCreateddateLessThanOrEqualTo(Date value) {
			addCriterion("CreatedDate <=", value, "createddate");
			return (Criteria) this;
		}

		public Criteria andCreateddateIn(List<Date> values) {
			addCriterion("CreatedDate in", values, "createddate");
			return (Criteria) this;
		}

		public Criteria andCreateddateNotIn(List<Date> values) {
			addCriterion("CreatedDate not in", values, "createddate");
			return (Criteria) this;
		}

		public Criteria andCreateddateBetween(Date value1, Date value2) {
			addCriterion("CreatedDate between", value1, value2, "createddate");
			return (Criteria) this;
		}

		public Criteria andCreateddateNotBetween(Date value1, Date value2) {
			addCriterion("CreatedDate not between", value1, value2,
					"createddate");
			return (Criteria) this;
		}

		public Criteria andModifieddateIsNull() {
			addCriterion("ModifiedDate is null");
			return (Criteria) this;
		}

		public Criteria andModifieddateIsNotNull() {
			addCriterion("ModifiedDate is not null");
			return (Criteria) this;
		}

		public Criteria andModifieddateEqualTo(Date value) {
			addCriterion("ModifiedDate =", value, "modifieddate");
			return (Criteria) this;
		}

		public Criteria andModifieddateNotEqualTo(Date value) {
			addCriterion("ModifiedDate <>", value, "modifieddate");
			return (Criteria) this;
		}

		public Criteria andModifieddateGreaterThan(Date value) {
			addCriterion("ModifiedDate >", value, "modifieddate");
			return (Criteria) this;
		}

		public Criteria andModifieddateGreaterThanOrEqualTo(Date value) {
			addCriterion("ModifiedDate >=", value, "modifieddate");
			return (Criteria) this;
		}

		public Criteria andModifieddateLessThan(Date value) {
			addCriterion("ModifiedDate <", value, "modifieddate");
			return (Criteria) this;
		}

		public Criteria andModifieddateLessThanOrEqualTo(Date value) {
			addCriterion("ModifiedDate <=", value, "modifieddate");
			return (Criteria) this;
		}

		public Criteria andModifieddateIn(List<Date> values) {
			addCriterion("ModifiedDate in", values, "modifieddate");
			return (Criteria) this;
		}

		public Criteria andModifieddateNotIn(List<Date> values) {
			addCriterion("ModifiedDate not in", values, "modifieddate");
			return (Criteria) this;
		}

		public Criteria andModifieddateBetween(Date value1, Date value2) {
			addCriterion("ModifiedDate between", value1, value2, "modifieddate");
			return (Criteria) this;
		}

		public Criteria andModifieddateNotBetween(Date value1, Date value2) {
			addCriterion("ModifiedDate not between", value1, value2,
					"modifieddate");
			return (Criteria) this;
		}

		public Criteria andIsdeletedIsNull() {
			addCriterion("IsDeleted is null");
			return (Criteria) this;
		}

		public Criteria andIsdeletedIsNotNull() {
			addCriterion("IsDeleted is not null");
			return (Criteria) this;
		}

		public Criteria andIsdeletedEqualTo(Boolean value) {
			addCriterion("IsDeleted =", value, "isdeleted");
			return (Criteria) this;
		}

		public Criteria andIsdeletedNotEqualTo(Boolean value) {
			addCriterion("IsDeleted <>", value, "isdeleted");
			return (Criteria) this;
		}

		public Criteria andIsdeletedGreaterThan(Boolean value) {
			addCriterion("IsDeleted >", value, "isdeleted");
			return (Criteria) this;
		}

		public Criteria andIsdeletedGreaterThanOrEqualTo(Boolean value) {
			addCriterion("IsDeleted >=", value, "isdeleted");
			return (Criteria) this;
		}

		public Criteria andIsdeletedLessThan(Boolean value) {
			addCriterion("IsDeleted <", value, "isdeleted");
			return (Criteria) this;
		}

		public Criteria andIsdeletedLessThanOrEqualTo(Boolean value) {
			addCriterion("IsDeleted <=", value, "isdeleted");
			return (Criteria) this;
		}

		public Criteria andIsdeletedIn(List<Boolean> values) {
			addCriterion("IsDeleted in", values, "isdeleted");
			return (Criteria) this;
		}

		public Criteria andIsdeletedNotIn(List<Boolean> values) {
			addCriterion("IsDeleted not in", values, "isdeleted");
			return (Criteria) this;
		}

		public Criteria andIsdeletedBetween(Boolean value1, Boolean value2) {
			addCriterion("IsDeleted between", value1, value2, "isdeleted");
			return (Criteria) this;
		}

		public Criteria andIsdeletedNotBetween(Boolean value1, Boolean value2) {
			addCriterion("IsDeleted not between", value1, value2, "isdeleted");
			return (Criteria) this;
		}

		public Criteria andBirthdayIsNull() {
			addCriterion("Birthday is null");
			return (Criteria) this;
		}

		public Criteria andBirthdayIsNotNull() {
			addCriterion("Birthday is not null");
			return (Criteria) this;
		}

		public Criteria andBirthdayEqualTo(Date value) {
			addCriterion("Birthday =", value, "birthday");
			return (Criteria) this;
		}

		public Criteria andBirthdayNotEqualTo(Date value) {
			addCriterion("Birthday <>", value, "birthday");
			return (Criteria) this;
		}

		public Criteria andBirthdayGreaterThan(Date value) {
			addCriterion("Birthday >", value, "birthday");
			return (Criteria) this;
		}

		public Criteria andBirthdayGreaterThanOrEqualTo(Date value) {
			addCriterion("Birthday >=", value, "birthday");
			return (Criteria) this;
		}

		public Criteria andBirthdayLessThan(Date value) {
			addCriterion("Birthday <", value, "birthday");
			return (Criteria) this;
		}

		public Criteria andBirthdayLessThanOrEqualTo(Date value) {
			addCriterion("Birthday <=", value, "birthday");
			return (Criteria) this;
		}

		public Criteria andBirthdayIn(List<Date> values) {
			addCriterion("Birthday in", values, "birthday");
			return (Criteria) this;
		}

		public Criteria andBirthdayNotIn(List<Date> values) {
			addCriterion("Birthday not in", values, "birthday");
			return (Criteria) this;
		}

		public Criteria andBirthdayBetween(Date value1, Date value2) {
			addCriterion("Birthday between", value1, value2, "birthday");
			return (Criteria) this;
		}

		public Criteria andBirthdayNotBetween(Date value1, Date value2) {
			addCriterion("Birthday not between", value1, value2, "birthday");
			return (Criteria) this;
		}

		public Criteria andGenderIsNull() {
			addCriterion("Gender is null");
			return (Criteria) this;
		}

		public Criteria andGenderIsNotNull() {
			addCriterion("Gender is not null");
			return (Criteria) this;
		}

		public Criteria andGenderEqualTo(Boolean value) {
			addCriterion("Gender =", value, "gender");
			return (Criteria) this;
		}

		public Criteria andGenderNotEqualTo(Boolean value) {
			addCriterion("Gender <>", value, "gender");
			return (Criteria) this;
		}

		public Criteria andGenderGreaterThan(Boolean value) {
			addCriterion("Gender >", value, "gender");
			return (Criteria) this;
		}

		public Criteria andGenderGreaterThanOrEqualTo(Boolean value) {
			addCriterion("Gender >=", value, "gender");
			return (Criteria) this;
		}

		public Criteria andGenderLessThan(Boolean value) {
			addCriterion("Gender <", value, "gender");
			return (Criteria) this;
		}

		public Criteria andGenderLessThanOrEqualTo(Boolean value) {
			addCriterion("Gender <=", value, "gender");
			return (Criteria) this;
		}

		public Criteria andGenderIn(List<Boolean> values) {
			addCriterion("Gender in", values, "gender");
			return (Criteria) this;
		}

		public Criteria andGenderNotIn(List<Boolean> values) {
			addCriterion("Gender not in", values, "gender");
			return (Criteria) this;
		}

		public Criteria andGenderBetween(Boolean value1, Boolean value2) {
			addCriterion("Gender between", value1, value2, "gender");
			return (Criteria) this;
		}

		public Criteria andGenderNotBetween(Boolean value1, Boolean value2) {
			addCriterion("Gender not between", value1, value2, "gender");
			return (Criteria) this;
		}

		public Criteria andUsersignatureIsNull() {
			addCriterion("UserSignature is null");
			return (Criteria) this;
		}

		public Criteria andUsersignatureIsNotNull() {
			addCriterion("UserSignature is not null");
			return (Criteria) this;
		}

		public Criteria andUsersignatureEqualTo(String value) {
			addCriterion("UserSignature =", value, "usersignature");
			return (Criteria) this;
		}

		public Criteria andUsersignatureNotEqualTo(String value) {
			addCriterion("UserSignature <>", value, "usersignature");
			return (Criteria) this;
		}

		public Criteria andUsersignatureGreaterThan(String value) {
			addCriterion("UserSignature >", value, "usersignature");
			return (Criteria) this;
		}

		public Criteria andUsersignatureGreaterThanOrEqualTo(String value) {
			addCriterion("UserSignature >=", value, "usersignature");
			return (Criteria) this;
		}

		public Criteria andUsersignatureLessThan(String value) {
			addCriterion("UserSignature <", value, "usersignature");
			return (Criteria) this;
		}

		public Criteria andUsersignatureLessThanOrEqualTo(String value) {
			addCriterion("UserSignature <=", value, "usersignature");
			return (Criteria) this;
		}

		public Criteria andUsersignatureLike(String value) {
			addCriterion("UserSignature like", value, "usersignature");
			return (Criteria) this;
		}

		public Criteria andUsersignatureNotLike(String value) {
			addCriterion("UserSignature not like", value, "usersignature");
			return (Criteria) this;
		}

		public Criteria andUsersignatureIn(List<String> values) {
			addCriterion("UserSignature in", values, "usersignature");
			return (Criteria) this;
		}

		public Criteria andUsersignatureNotIn(List<String> values) {
			addCriterion("UserSignature not in", values, "usersignature");
			return (Criteria) this;
		}

		public Criteria andUsersignatureBetween(String value1, String value2) {
			addCriterion("UserSignature between", value1, value2,
					"usersignature");
			return (Criteria) this;
		}

		public Criteria andUsersignatureNotBetween(String value1, String value2) {
			addCriterion("UserSignature not between", value1, value2,
					"usersignature");
			return (Criteria) this;
		}

		public Criteria andAvataridfkIsNull() {
			addCriterion("AvatarIDFK is null");
			return (Criteria) this;
		}

		public Criteria andAvataridfkIsNotNull() {
			addCriterion("AvatarIDFK is not null");
			return (Criteria) this;
		}

		public Criteria andAvataridfkEqualTo(String value) {
			addCriterion("AvatarIDFK =", value, "avataridfk");
			return (Criteria) this;
		}

		public Criteria andAvataridfkNotEqualTo(String value) {
			addCriterion("AvatarIDFK <>", value, "avataridfk");
			return (Criteria) this;
		}

		public Criteria andAvataridfkGreaterThan(String value) {
			addCriterion("AvatarIDFK >", value, "avataridfk");
			return (Criteria) this;
		}

		public Criteria andAvataridfkGreaterThanOrEqualTo(String value) {
			addCriterion("AvatarIDFK >=", value, "avataridfk");
			return (Criteria) this;
		}

		public Criteria andAvataridfkLessThan(String value) {
			addCriterion("AvatarIDFK <", value, "avataridfk");
			return (Criteria) this;
		}

		public Criteria andAvataridfkLessThanOrEqualTo(String value) {
			addCriterion("AvatarIDFK <=", value, "avataridfk");
			return (Criteria) this;
		}

		public Criteria andAvataridfkLike(String value) {
			addCriterion("AvatarIDFK like", value, "avataridfk");
			return (Criteria) this;
		}

		public Criteria andAvataridfkNotLike(String value) {
			addCriterion("AvatarIDFK not like", value, "avataridfk");
			return (Criteria) this;
		}

		public Criteria andAvataridfkIn(List<String> values) {
			addCriterion("AvatarIDFK in", values, "avataridfk");
			return (Criteria) this;
		}

		public Criteria andAvataridfkNotIn(List<String> values) {
			addCriterion("AvatarIDFK not in", values, "avataridfk");
			return (Criteria) this;
		}

		public Criteria andAvataridfkBetween(String value1, String value2) {
			addCriterion("AvatarIDFK between", value1, value2, "avataridfk");
			return (Criteria) this;
		}

		public Criteria andAvataridfkNotBetween(String value1, String value2) {
			addCriterion("AvatarIDFK not between", value1, value2, "avataridfk");
			return (Criteria) this;
		}

		public Criteria andFriendcountIsNull() {
			addCriterion("FriendCount is null");
			return (Criteria) this;
		}

		public Criteria andFriendcountIsNotNull() {
			addCriterion("FriendCount is not null");
			return (Criteria) this;
		}

		public Criteria andFriendcountEqualTo(Integer value) {
			addCriterion("FriendCount =", value, "friendcount");
			return (Criteria) this;
		}

		public Criteria andFriendcountNotEqualTo(Integer value) {
			addCriterion("FriendCount <>", value, "friendcount");
			return (Criteria) this;
		}

		public Criteria andFriendcountGreaterThan(Integer value) {
			addCriterion("FriendCount >", value, "friendcount");
			return (Criteria) this;
		}

		public Criteria andFriendcountGreaterThanOrEqualTo(Integer value) {
			addCriterion("FriendCount >=", value, "friendcount");
			return (Criteria) this;
		}

		public Criteria andFriendcountLessThan(Integer value) {
			addCriterion("FriendCount <", value, "friendcount");
			return (Criteria) this;
		}

		public Criteria andFriendcountLessThanOrEqualTo(Integer value) {
			addCriterion("FriendCount <=", value, "friendcount");
			return (Criteria) this;
		}

		public Criteria andFriendcountIn(List<Integer> values) {
			addCriterion("FriendCount in", values, "friendcount");
			return (Criteria) this;
		}

		public Criteria andFriendcountNotIn(List<Integer> values) {
			addCriterion("FriendCount not in", values, "friendcount");
			return (Criteria) this;
		}

		public Criteria andFriendcountBetween(Integer value1, Integer value2) {
			addCriterion("FriendCount between", value1, value2, "friendcount");
			return (Criteria) this;
		}

		public Criteria andFriendcountNotBetween(Integer value1, Integer value2) {
			addCriterion("FriendCount not between", value1, value2,
					"friendcount");
			return (Criteria) this;
		}

		public Criteria andFancountIsNull() {
			addCriterion("FanCount is null");
			return (Criteria) this;
		}

		public Criteria andFancountIsNotNull() {
			addCriterion("FanCount is not null");
			return (Criteria) this;
		}

		public Criteria andFancountEqualTo(Integer value) {
			addCriterion("FanCount =", value, "fancount");
			return (Criteria) this;
		}

		public Criteria andFancountNotEqualTo(Integer value) {
			addCriterion("FanCount <>", value, "fancount");
			return (Criteria) this;
		}

		public Criteria andFancountGreaterThan(Integer value) {
			addCriterion("FanCount >", value, "fancount");
			return (Criteria) this;
		}

		public Criteria andFancountGreaterThanOrEqualTo(Integer value) {
			addCriterion("FanCount >=", value, "fancount");
			return (Criteria) this;
		}

		public Criteria andFancountLessThan(Integer value) {
			addCriterion("FanCount <", value, "fancount");
			return (Criteria) this;
		}

		public Criteria andFancountLessThanOrEqualTo(Integer value) {
			addCriterion("FanCount <=", value, "fancount");
			return (Criteria) this;
		}

		public Criteria andFancountIn(List<Integer> values) {
			addCriterion("FanCount in", values, "fancount");
			return (Criteria) this;
		}

		public Criteria andFancountNotIn(List<Integer> values) {
			addCriterion("FanCount not in", values, "fancount");
			return (Criteria) this;
		}

		public Criteria andFancountBetween(Integer value1, Integer value2) {
			addCriterion("FanCount between", value1, value2, "fancount");
			return (Criteria) this;
		}

		public Criteria andFancountNotBetween(Integer value1, Integer value2) {
			addCriterion("FanCount not between", value1, value2, "fancount");
			return (Criteria) this;
		}

		public Criteria andFollowcountIsNull() {
			addCriterion("FollowCount is null");
			return (Criteria) this;
		}

		public Criteria andFollowcountIsNotNull() {
			addCriterion("FollowCount is not null");
			return (Criteria) this;
		}

		public Criteria andFollowcountEqualTo(Integer value) {
			addCriterion("FollowCount =", value, "followcount");
			return (Criteria) this;
		}

		public Criteria andFollowcountNotEqualTo(Integer value) {
			addCriterion("FollowCount <>", value, "followcount");
			return (Criteria) this;
		}

		public Criteria andFollowcountGreaterThan(Integer value) {
			addCriterion("FollowCount >", value, "followcount");
			return (Criteria) this;
		}

		public Criteria andFollowcountGreaterThanOrEqualTo(Integer value) {
			addCriterion("FollowCount >=", value, "followcount");
			return (Criteria) this;
		}

		public Criteria andFollowcountLessThan(Integer value) {
			addCriterion("FollowCount <", value, "followcount");
			return (Criteria) this;
		}

		public Criteria andFollowcountLessThanOrEqualTo(Integer value) {
			addCriterion("FollowCount <=", value, "followcount");
			return (Criteria) this;
		}

		public Criteria andFollowcountIn(List<Integer> values) {
			addCriterion("FollowCount in", values, "followcount");
			return (Criteria) this;
		}

		public Criteria andFollowcountNotIn(List<Integer> values) {
			addCriterion("FollowCount not in", values, "followcount");
			return (Criteria) this;
		}

		public Criteria andFollowcountBetween(Integer value1, Integer value2) {
			addCriterion("FollowCount between", value1, value2, "followcount");
			return (Criteria) this;
		}

		public Criteria andFollowcountNotBetween(Integer value1, Integer value2) {
			addCriterion("FollowCount not between", value1, value2,
					"followcount");
			return (Criteria) this;
		}

		public Criteria andArticlecountIsNull() {
			addCriterion("ArticleCount is null");
			return (Criteria) this;
		}

		public Criteria andArticlecountIsNotNull() {
			addCriterion("ArticleCount is not null");
			return (Criteria) this;
		}

		public Criteria andArticlecountEqualTo(Integer value) {
			addCriterion("ArticleCount =", value, "articlecount");
			return (Criteria) this;
		}

		public Criteria andArticlecountNotEqualTo(Integer value) {
			addCriterion("ArticleCount <>", value, "articlecount");
			return (Criteria) this;
		}

		public Criteria andArticlecountGreaterThan(Integer value) {
			addCriterion("ArticleCount >", value, "articlecount");
			return (Criteria) this;
		}

		public Criteria andArticlecountGreaterThanOrEqualTo(Integer value) {
			addCriterion("ArticleCount >=", value, "articlecount");
			return (Criteria) this;
		}

		public Criteria andArticlecountLessThan(Integer value) {
			addCriterion("ArticleCount <", value, "articlecount");
			return (Criteria) this;
		}

		public Criteria andArticlecountLessThanOrEqualTo(Integer value) {
			addCriterion("ArticleCount <=", value, "articlecount");
			return (Criteria) this;
		}

		public Criteria andArticlecountIn(List<Integer> values) {
			addCriterion("ArticleCount in", values, "articlecount");
			return (Criteria) this;
		}

		public Criteria andArticlecountNotIn(List<Integer> values) {
			addCriterion("ArticleCount not in", values, "articlecount");
			return (Criteria) this;
		}

		public Criteria andArticlecountBetween(Integer value1, Integer value2) {
			addCriterion("ArticleCount between", value1, value2, "articlecount");
			return (Criteria) this;
		}

		public Criteria andArticlecountNotBetween(Integer value1, Integer value2) {
			addCriterion("ArticleCount not between", value1, value2,
					"articlecount");
			return (Criteria) this;
		}

		public Criteria andRegisterfromIsNull() {
			addCriterion("RegisterFrom is null");
			return (Criteria) this;
		}

		public Criteria andRegisterfromIsNotNull() {
			addCriterion("RegisterFrom is not null");
			return (Criteria) this;
		}

		public Criteria andRegisterfromEqualTo(Integer value) {
			addCriterion("RegisterFrom =", value, "registerfrom");
			return (Criteria) this;
		}

		public Criteria andRegisterfromNotEqualTo(Integer value) {
			addCriterion("RegisterFrom <>", value, "registerfrom");
			return (Criteria) this;
		}

		public Criteria andRegisterfromGreaterThan(Integer value) {
			addCriterion("RegisterFrom >", value, "registerfrom");
			return (Criteria) this;
		}

		public Criteria andRegisterfromGreaterThanOrEqualTo(Integer value) {
			addCriterion("RegisterFrom >=", value, "registerfrom");
			return (Criteria) this;
		}

		public Criteria andRegisterfromLessThan(Integer value) {
			addCriterion("RegisterFrom <", value, "registerfrom");
			return (Criteria) this;
		}

		public Criteria andRegisterfromLessThanOrEqualTo(Integer value) {
			addCriterion("RegisterFrom <=", value, "registerfrom");
			return (Criteria) this;
		}

		public Criteria andRegisterfromIn(List<Integer> values) {
			addCriterion("RegisterFrom in", values, "registerfrom");
			return (Criteria) this;
		}

		public Criteria andRegisterfromNotIn(List<Integer> values) {
			addCriterion("RegisterFrom not in", values, "registerfrom");
			return (Criteria) this;
		}

		public Criteria andRegisterfromBetween(Integer value1, Integer value2) {
			addCriterion("RegisterFrom between", value1, value2, "registerfrom");
			return (Criteria) this;
		}

		public Criteria andRegisterfromNotBetween(Integer value1, Integer value2) {
			addCriterion("RegisterFrom not between", value1, value2,
					"registerfrom");
			return (Criteria) this;
		}

		public Criteria andBackgroundurlIsNull() {
			addCriterion("BackgroundUrl is null");
			return (Criteria) this;
		}

		public Criteria andBackgroundurlIsNotNull() {
			addCriterion("BackgroundUrl is not null");
			return (Criteria) this;
		}

		public Criteria andBackgroundurlEqualTo(String value) {
			addCriterion("BackgroundUrl =", value, "backgroundurl");
			return (Criteria) this;
		}

		public Criteria andBackgroundurlNotEqualTo(String value) {
			addCriterion("BackgroundUrl <>", value, "backgroundurl");
			return (Criteria) this;
		}

		public Criteria andBackgroundurlGreaterThan(String value) {
			addCriterion("BackgroundUrl >", value, "backgroundurl");
			return (Criteria) this;
		}

		public Criteria andBackgroundurlGreaterThanOrEqualTo(String value) {
			addCriterion("BackgroundUrl >=", value, "backgroundurl");
			return (Criteria) this;
		}

		public Criteria andBackgroundurlLessThan(String value) {
			addCriterion("BackgroundUrl <", value, "backgroundurl");
			return (Criteria) this;
		}

		public Criteria andBackgroundurlLessThanOrEqualTo(String value) {
			addCriterion("BackgroundUrl <=", value, "backgroundurl");
			return (Criteria) this;
		}

		public Criteria andBackgroundurlLike(String value) {
			addCriterion("BackgroundUrl like", value, "backgroundurl");
			return (Criteria) this;
		}

		public Criteria andBackgroundurlNotLike(String value) {
			addCriterion("BackgroundUrl not like", value, "backgroundurl");
			return (Criteria) this;
		}

		public Criteria andBackgroundurlIn(List<String> values) {
			addCriterion("BackgroundUrl in", values, "backgroundurl");
			return (Criteria) this;
		}

		public Criteria andBackgroundurlNotIn(List<String> values) {
			addCriterion("BackgroundUrl not in", values, "backgroundurl");
			return (Criteria) this;
		}

		public Criteria andBackgroundurlBetween(String value1, String value2) {
			addCriterion("BackgroundUrl between", value1, value2,
					"backgroundurl");
			return (Criteria) this;
		}

		public Criteria andBackgroundurlNotBetween(String value1, String value2) {
			addCriterion("BackgroundUrl not between", value1, value2,
					"backgroundurl");
			return (Criteria) this;
		}

		public Criteria andPhonenumberIsNull() {
			addCriterion("PhoneNumber is null");
			return (Criteria) this;
		}

		public Criteria andPhonenumberIsNotNull() {
			addCriterion("PhoneNumber is not null");
			return (Criteria) this;
		}

		public Criteria andPhonenumberEqualTo(String value) {
			addCriterion("PhoneNumber =", value, "phonenumber");
			return (Criteria) this;
		}

		public Criteria andPhonenumberNotEqualTo(String value) {
			addCriterion("PhoneNumber <>", value, "phonenumber");
			return (Criteria) this;
		}

		public Criteria andPhonenumberGreaterThan(String value) {
			addCriterion("PhoneNumber >", value, "phonenumber");
			return (Criteria) this;
		}

		public Criteria andPhonenumberGreaterThanOrEqualTo(String value) {
			addCriterion("PhoneNumber >=", value, "phonenumber");
			return (Criteria) this;
		}

		public Criteria andPhonenumberLessThan(String value) {
			addCriterion("PhoneNumber <", value, "phonenumber");
			return (Criteria) this;
		}

		public Criteria andPhonenumberLessThanOrEqualTo(String value) {
			addCriterion("PhoneNumber <=", value, "phonenumber");
			return (Criteria) this;
		}

		public Criteria andPhonenumberLike(String value) {
			addCriterion("PhoneNumber like", value, "phonenumber");
			return (Criteria) this;
		}

		public Criteria andPhonenumberNotLike(String value) {
			addCriterion("PhoneNumber not like", value, "phonenumber");
			return (Criteria) this;
		}

		public Criteria andPhonenumberIn(List<String> values) {
			addCriterion("PhoneNumber in", values, "phonenumber");
			return (Criteria) this;
		}

		public Criteria andPhonenumberNotIn(List<String> values) {
			addCriterion("PhoneNumber not in", values, "phonenumber");
			return (Criteria) this;
		}

		public Criteria andPhonenumberBetween(String value1, String value2) {
			addCriterion("PhoneNumber between", value1, value2, "phonenumber");
			return (Criteria) this;
		}

		public Criteria andPhonenumberNotBetween(String value1, String value2) {
			addCriterion("PhoneNumber not between", value1, value2,
					"phonenumber");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table tb_user
	 * @mbggenerated  Thu Oct 31 10:13:08 CST 2013
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_user
     *
     * @mbggenerated do_not_delete_during_merge Sat Oct 26 13:40:24 CST 2013
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}