package com.dandelion.memberapp.dao.model;

import java.util.Date;

public class Wsusersession {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_wsusersession.ID
     *
     * @mbggenerated Sun Oct 27 22:52:00 CST 2013
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_wsusersession.SessionKey
     *
     * @mbggenerated Sun Oct 27 22:52:00 CST 2013
     */
    private Integer sessionkey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_wsusersession.UserIDFK
     *
     * @mbggenerated Sun Oct 27 22:52:00 CST 2013
     */
    private String useridfk;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_wsusersession.DeviceIdentifier
     *
     * @mbggenerated Sun Oct 27 22:52:00 CST 2013
     */
    private String deviceidentifier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_wsusersession.PackageName
     *
     * @mbggenerated Sun Oct 27 22:52:00 CST 2013
     */
    private String packagename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_wsusersession.CreatedDate
     *
     * @mbggenerated Sun Oct 27 22:52:00 CST 2013
     */
    private Date createddate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_wsusersession.ID
     *
     * @return the value of tb_wsusersession.ID
     *
     * @mbggenerated Sun Oct 27 22:52:00 CST 2013
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_wsusersession.ID
     *
     * @param id the value for tb_wsusersession.ID
     *
     * @mbggenerated Sun Oct 27 22:52:00 CST 2013
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_wsusersession.SessionKey
     *
     * @return the value of tb_wsusersession.SessionKey
     *
     * @mbggenerated Sun Oct 27 22:52:00 CST 2013
     */
    public Integer getSessionkey() {
        return sessionkey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_wsusersession.SessionKey
     *
     * @param sessionkey the value for tb_wsusersession.SessionKey
     *
     * @mbggenerated Sun Oct 27 22:52:00 CST 2013
     */
    public void setSessionkey(Integer sessionkey) {
        this.sessionkey = sessionkey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_wsusersession.UserIDFK
     *
     * @return the value of tb_wsusersession.UserIDFK
     *
     * @mbggenerated Sun Oct 27 22:52:00 CST 2013
     */
    public String getUseridfk() {
        return useridfk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_wsusersession.UserIDFK
     *
     * @param useridfk the value for tb_wsusersession.UserIDFK
     *
     * @mbggenerated Sun Oct 27 22:52:00 CST 2013
     */
    public void setUseridfk(String useridfk) {
        this.useridfk = useridfk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_wsusersession.DeviceIdentifier
     *
     * @return the value of tb_wsusersession.DeviceIdentifier
     *
     * @mbggenerated Sun Oct 27 22:52:00 CST 2013
     */
    public String getDeviceidentifier() {
        return deviceidentifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_wsusersession.DeviceIdentifier
     *
     * @param deviceidentifier the value for tb_wsusersession.DeviceIdentifier
     *
     * @mbggenerated Sun Oct 27 22:52:00 CST 2013
     */
    public void setDeviceidentifier(String deviceidentifier) {
        this.deviceidentifier = deviceidentifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_wsusersession.PackageName
     *
     * @return the value of tb_wsusersession.PackageName
     *
     * @mbggenerated Sun Oct 27 22:52:00 CST 2013
     */
    public String getPackagename() {
        return packagename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_wsusersession.PackageName
     *
     * @param packagename the value for tb_wsusersession.PackageName
     *
     * @mbggenerated Sun Oct 27 22:52:00 CST 2013
     */
    public void setPackagename(String packagename) {
        this.packagename = packagename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_wsusersession.CreatedDate
     *
     * @return the value of tb_wsusersession.CreatedDate
     *
     * @mbggenerated Sun Oct 27 22:52:00 CST 2013
     */
    public Date getCreateddate() {
        return createddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_wsusersession.CreatedDate
     *
     * @param createddate the value for tb_wsusersession.CreatedDate
     *
     * @mbggenerated Sun Oct 27 22:52:00 CST 2013
     */
    public void setCreateddate(Date createddate) {
        this.createddate = createddate;
    }
}