package com.dandelion.memberapp.dao.data;

import com.dandelion.memberapp.dao.model.Emailbean;
import com.dandelion.memberapp.dao.model.EmailbeanExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EmailbeanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_emailbean
     *
     * @mbggenerated Tue Oct 29 17:49:28 CST 2013
     */
    int countByExample(EmailbeanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_emailbean
     *
     * @mbggenerated Tue Oct 29 17:49:28 CST 2013
     */
    int deleteByExample(EmailbeanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_emailbean
     *
     * @mbggenerated Tue Oct 29 17:49:28 CST 2013
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_emailbean
     *
     * @mbggenerated Tue Oct 29 17:49:28 CST 2013
     */
    int insert(Emailbean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_emailbean
     *
     * @mbggenerated Tue Oct 29 17:49:28 CST 2013
     */
    int insertSelective(Emailbean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_emailbean
     *
     * @mbggenerated Tue Oct 29 17:49:28 CST 2013
     */
    List<Emailbean> selectByExample(EmailbeanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_emailbean
     *
     * @mbggenerated Tue Oct 29 17:49:28 CST 2013
     */
    Emailbean selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_emailbean
     *
     * @mbggenerated Tue Oct 29 17:49:28 CST 2013
     */
    int updateByExampleSelective(@Param("record") Emailbean record, @Param("example") EmailbeanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_emailbean
     *
     * @mbggenerated Tue Oct 29 17:49:28 CST 2013
     */
    int updateByExample(@Param("record") Emailbean record, @Param("example") EmailbeanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_emailbean
     *
     * @mbggenerated Tue Oct 29 17:49:28 CST 2013
     */
    int updateByPrimaryKeySelective(Emailbean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_emailbean
     *
     * @mbggenerated Tue Oct 29 17:49:28 CST 2013
     */
    int updateByPrimaryKey(Emailbean record);
}