package com.dandelion.memberapp.dao.data;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.dandelion.memberapp.model.po.Emailbean;
import com.dandelion.memberapp.model.po.EmailbeanExample;

public interface EmailbeanMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_emailbean
	 * @mbggenerated  Thu Jan 16 19:58:43 CST 2014
	 */
	int countByExample(EmailbeanExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_emailbean
	 * @mbggenerated  Thu Jan 16 19:58:43 CST 2014
	 */
	int deleteByExample(EmailbeanExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_emailbean
	 * @mbggenerated  Thu Jan 16 19:58:43 CST 2014
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_emailbean
	 * @mbggenerated  Thu Jan 16 19:58:43 CST 2014
	 */
	int insert(Emailbean record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_emailbean
	 * @mbggenerated  Thu Jan 16 19:58:43 CST 2014
	 */
	int insertSelective(Emailbean record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_emailbean
	 * @mbggenerated  Thu Jan 16 19:58:43 CST 2014
	 */
	List<Emailbean> selectByExample(EmailbeanExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_emailbean
	 * @mbggenerated  Thu Jan 16 19:58:43 CST 2014
	 */
	Emailbean selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_emailbean
	 * @mbggenerated  Thu Jan 16 19:58:43 CST 2014
	 */
	int updateByExampleSelective(@Param("record") Emailbean record,
			@Param("example") EmailbeanExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_emailbean
	 * @mbggenerated  Thu Jan 16 19:58:43 CST 2014
	 */
	int updateByExample(@Param("record") Emailbean record,
			@Param("example") EmailbeanExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_emailbean
	 * @mbggenerated  Thu Jan 16 19:58:43 CST 2014
	 */
	int updateByPrimaryKeySelective(Emailbean record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_emailbean
	 * @mbggenerated  Thu Jan 16 19:58:43 CST 2014
	 */
	int updateByPrimaryKey(Emailbean record);
}