package com.dandelion.memberapp.dao.data;

import com.dandelion.memberapp.model.po.Feed;
import com.dandelion.memberapp.model.po.FeedExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FeedMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_feed
	 * @mbggenerated  Thu Jan 16 19:58:43 CST 2014
	 */
	int countByExample(FeedExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_feed
	 * @mbggenerated  Thu Jan 16 19:58:43 CST 2014
	 */
	int deleteByExample(FeedExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_feed
	 * @mbggenerated  Thu Jan 16 19:58:43 CST 2014
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_feed
	 * @mbggenerated  Thu Jan 16 19:58:43 CST 2014
	 */
	int insert(Feed record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_feed
	 * @mbggenerated  Thu Jan 16 19:58:43 CST 2014
	 */
	int insertSelective(Feed record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_feed
	 * @mbggenerated  Thu Jan 16 19:58:43 CST 2014
	 */
	List<Feed> selectByExample(FeedExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_feed
	 * @mbggenerated  Thu Jan 16 19:58:43 CST 2014
	 */
	Feed selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_feed
	 * @mbggenerated  Thu Jan 16 19:58:43 CST 2014
	 */
	int updateByExampleSelective(@Param("record") Feed record,
			@Param("example") FeedExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_feed
	 * @mbggenerated  Thu Jan 16 19:58:43 CST 2014
	 */
	int updateByExample(@Param("record") Feed record,
			@Param("example") FeedExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_feed
	 * @mbggenerated  Thu Jan 16 19:58:43 CST 2014
	 */
	int updateByPrimaryKeySelective(Feed record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_feed
	 * @mbggenerated  Thu Jan 16 19:58:43 CST 2014
	 */
	int updateByPrimaryKey(Feed record);
}