package com.dandelion.memberapp.dao.data;

import com.dandelion.memberapp.model.po.Friend;
import com.dandelion.memberapp.model.po.FriendExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FriendMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_friend
	 * @mbggenerated  Thu Jan 16 19:58:43 CST 2014
	 */
	int countByExample(FriendExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_friend
	 * @mbggenerated  Thu Jan 16 19:58:43 CST 2014
	 */
	int deleteByExample(FriendExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_friend
	 * @mbggenerated  Thu Jan 16 19:58:43 CST 2014
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_friend
	 * @mbggenerated  Thu Jan 16 19:58:43 CST 2014
	 */
	int insert(Friend record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_friend
	 * @mbggenerated  Thu Jan 16 19:58:43 CST 2014
	 */
	int insertSelective(Friend record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_friend
	 * @mbggenerated  Thu Jan 16 19:58:43 CST 2014
	 */
	List<Friend> selectByExample(FriendExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_friend
	 * @mbggenerated  Thu Jan 16 19:58:43 CST 2014
	 */
	Friend selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_friend
	 * @mbggenerated  Thu Jan 16 19:58:43 CST 2014
	 */
	int updateByExampleSelective(@Param("record") Friend record,
			@Param("example") FriendExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_friend
	 * @mbggenerated  Thu Jan 16 19:58:43 CST 2014
	 */
	int updateByExample(@Param("record") Friend record,
			@Param("example") FriendExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_friend
	 * @mbggenerated  Thu Jan 16 19:58:43 CST 2014
	 */
	int updateByPrimaryKeySelective(Friend record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_friend
	 * @mbggenerated  Thu Jan 16 19:58:43 CST 2014
	 */
	int updateByPrimaryKey(Friend record);
}