package com.dandelion.memberapp.dao.data;

import com.dandelion.memberapp.model.po.Notification;
import com.dandelion.memberapp.model.po.NotificationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface NotificationMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_notification
	 * @mbggenerated  Wed Jan 01 10:48:24 CST 2014
	 */
	int countByExample(NotificationExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_notification
	 * @mbggenerated  Wed Jan 01 10:48:24 CST 2014
	 */
	int deleteByExample(NotificationExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_notification
	 * @mbggenerated  Wed Jan 01 10:48:24 CST 2014
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_notification
	 * @mbggenerated  Wed Jan 01 10:48:24 CST 2014
	 */
	int insert(Notification record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_notification
	 * @mbggenerated  Wed Jan 01 10:48:24 CST 2014
	 */
	int insertSelective(Notification record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_notification
	 * @mbggenerated  Wed Jan 01 10:48:24 CST 2014
	 */
	List<Notification> selectByExample(NotificationExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_notification
	 * @mbggenerated  Wed Jan 01 10:48:24 CST 2014
	 */
	Notification selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_notification
	 * @mbggenerated  Wed Jan 01 10:48:24 CST 2014
	 */
	int updateByExampleSelective(@Param("record") Notification record,
			@Param("example") NotificationExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_notification
	 * @mbggenerated  Wed Jan 01 10:48:24 CST 2014
	 */
	int updateByExample(@Param("record") Notification record,
			@Param("example") NotificationExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_notification
	 * @mbggenerated  Wed Jan 01 10:48:24 CST 2014
	 */
	int updateByPrimaryKeySelective(Notification record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_notification
	 * @mbggenerated  Wed Jan 01 10:48:24 CST 2014
	 */
	int updateByPrimaryKey(Notification record);
}